Repository minio/minio, pull requests merged in 2018-12, with the labels that each got.

#6909 Redirect browser requests only if the browser is enabled
  cmd/api-response.go
Labels: regression fixed

#6926 Register notFound handler only once per root router
  cmd/storage-rest-server.go
Labels: priority: high, regression fixed

#6920 fix ConfigSys and NotificationSys initialization for NAS
  cmd/bucket-notification-handlers.go
  cmd/dummy-object-layer_test.go
  cmd/fs-v1.go
  cmd/gateway-main.go
  cmd/gateway-unsupported.go
  cmd/gateway/nas/gateway-nas.go
  cmd/object-api-interface.go
  cmd/xl-sets.go
  cmd/xl-v1-bucket.go
Labels: priority: high, regression fixed

#6523 add auto-encryption for SSE-S3 using a KMS
  cmd/admin-rpc_test.go
  cmd/bucket-handlers.go
  cmd/crypto/config.go
  cmd/environment.go
  cmd/gateway-main.go
  cmd/globals.go
  cmd/object-handlers.go
  cmd/server-main.go
  cmd/web-handlers.go
  docs/kms/README.md
Labels: priority: high

#6899 Add anonymous flag to prevent logging sensitive information
  cmd/common-main.go
  cmd/gateway-main.go
  cmd/gateway-startup-msg.go
  cmd/globals.go
  cmd/logger/logger.go
  cmd/main.go
  cmd/server-main.go
  cmd/server-startup-msg.go
Labels: priority: high
