Repository minio/minio, pull requests merged in 2018-08, with the labels that each got.

#5959 Simplify erasure code by separating bitrot from erasure code
  cmd/bitrot.go
  cmd/bitrot_test.go
  cmd/erasure-createfile.go
  cmd/erasure-createfile_test.go
  cmd/erasure-healfile.go
  cmd/erasure-healfile_test.go
  cmd/erasure-readfile.go
  cmd/erasure-readfile_test.go
  cmd/erasure-utils.go
  cmd/erasure.go
  cmd/erasure_test.go
  cmd/posix.go
  cmd/posix_test.go
  cmd/storage-errors.go
  cmd/storage-rpc-client.go
  cmd/storage-rpc_test.go
  cmd/xl-v1-common.go
  cmd/xl-v1-healing-common.go
  cmd/xl-v1-healing.go
  cmd/xl-v1-metadata.go
  cmd/xl-v1-multipart.go
  cmd/xl-v1-object.go
  cmd/xl-v1-utils_test.go
Labels: priority: high

#6186 Remove unnecessary error log messages
  cmd/fs-v1-helpers.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/s3/gateway-s3.go
  cmd/object-api-input-checks.go
  cmd/xl-v1-common.go
  cmd/xl-v1-multipart.go
  cmd/xl-v1-object.go
  cmd/xl-v1-utils.go
Labels: priority: high

#6294 Validate prefixes on all sets
  cmd/xl-sets.go
Labels: priority: high, regression

#6333 Initialize global object layer after all subsystems have initialized
  cmd/config-migrate_test.go
  cmd/config.go
  cmd/policy.go
  cmd/server-main.go
Labels: priority: high, regression

#6340 Avoid ListenBucket targets to be listed in ServerInfo
  cmd/notification.go
Labels: priority: high, regression

#6360 Fix WORM and BROWSER status calculation
  cmd/config-current.go
  cmd/config-current_test.go
  cmd/test-utils_test.go
Labels: regression fixed

#6366 Revert "Remove curl after the usage (#6347)"
  Dockerfile
  Dockerfile.dev
  Dockerfile.release
Labels: regression fixed

#6390 HTTP headers are case insensitive handle them appropriately
  cmd/http/listener.go
  cmd/http/listener_test.go
Labels: priority: high, regression fixed

#6398 Revert all GetObjectNInfo related PRs
  cmd/api-headers.go
  cmd/disk-cache.go
  cmd/dummy-object-layer_test.go
  cmd/encryption-v1.go
  cmd/fs-v1.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/b2/gateway-b2.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/manta/gateway-manta.go
  cmd/gateway/oss/gateway-oss.go
  cmd/gateway/s3/gateway-s3.go
  cmd/gateway/sia/gateway-sia.go
  cmd/httprange.go
  cmd/object-api-interface.go
  cmd/object-api-utils.go
  cmd/object-handlers.go
  cmd/xl-sets.go
  cmd/xl-v1-object.go
  pkg/ioutil/ioutil.go
Labels: priority: high

#6395 xl: Avoid removing a directory if it is not an object dir
  cmd/xl-v1-object.go
  cmd/xl-v1-object_test.go
Labels: regression fixed
