Repository minio/minio, pull requests merged in 2018-10, with the labels that each got.

#6563 Verify bitrot in ReadFile correctly when verifier is set
  cmd/storage-rpc-client.go
Labels: priority: high, regression fixed

#6620 fix travis CI build
  Makefile
Labels: priority: high

#6637 Add canned policy support
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/iam.go
  cmd/typed-errors.go
  docs/multi-user/README.md
  pkg/madmin/API.md
  pkg/madmin/examples/add-user-and-policy.go
  pkg/madmin/policy-commands.go
  pkg/madmin/user-commands.go
Labels: priority: high

#6640 Fix toggling users status
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/iam.go
  pkg/madmin/user-commands.go
Labels: priority: high

#6592 xl: Add '.CORRUPTED' prefix to corrupted objects
  cmd/xl-v1-object.go
Labels: priority: high

#6715 copy: Ensure that the user has GET access to source object
  cmd/object-handlers.go
  cmd/object-handlers_test.go
Labels: priority: severe

#6744 Fix mimedb update files
  pkg/mimedb/db.go
Labels: priority: high
