Repository minio/minio, pull requests merged in 2018-09, with the labels that each got.

#6421 xl: Fix removing an empty directory
  cmd/object-api-deleteobject_test.go
  cmd/object-api-getobject_test.go
  cmd/object-api-getobjectinfo_test.go
  cmd/object-api-listobjects_test.go
  cmd/xl-v1-object.go
Labels: regression fixed

#6432 return `Access Denied` for invalid SSE keys
  cmd/api-errors.go
  cmd/crypto/error.go
  cmd/crypto/key.go
Labels: regression fixed

#6428 Gateway should honour --address flag while checking port availability
  cmd/gateway-main.go
Labels: regression fixed

#6412 Show pointer when user hovers over folder name
  browser/app/less/inc/list.less
  browser/ui-assets.go
Labels: regression fixed

#6435 Allow backward compatible way to load creds from config.json
  cmd/common-main.go
  cmd/config.go
  cmd/server-main.go
Labels: priority: high

#6446 Rename config.json in config-dir with '.deprecated' extension
  cmd/config.go
  cmd/server-main.go
Labels: priority: high

#6457 Bump RPC version after ReadFile RPC arguments change
  cmd/globals.go
Labels: priority: high, regression fixed

#6465 Combine obtaining resource, host, method into one operation
  cmd/http/listener.go
  cmd/http/listener_test.go
Labels: regression fixed

#6489 Use GetObjectNInfo in CopyObject and CopyObjectPart
  cmd/api-headers.go
  cmd/copy-part-range.go
  cmd/crypto/header.go
  cmd/crypto/header_test.go
  cmd/disk-cache.go
  cmd/dummy-object-layer_test.go
  cmd/encryption-v1.go
  cmd/encryption-v1_test.go
  cmd/erasure-utils.go
  cmd/fs-v1-multipart.go
  cmd/fs-v1.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/b2/gateway-b2.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/manta/gateway-manta.go
  cmd/gateway/oss/gateway-oss.go
  cmd/gateway/s3/gateway-s3.go
  cmd/gateway/sia/gateway-sia.go
  cmd/object-api-interface.go
  cmd/object-api-utils.go
  cmd/object-handlers.go
  cmd/xl-sets.go
  cmd/xl-v1-multipart.go
  cmd/xl-v1-object.go
Labels: priority: high
