Repository minio/minio, pull requests merged in 2018-05, with the labels that each got.

#5889 fs: fix a regression allow reading of existing files
  cmd/fs-v1.go
Labels: priority: high

#5878 Enhance fatal errors printing of common issues seen by users
  cmd/certs.go
  cmd/common-main.go
  cmd/config-current.go
  cmd/disk-cache-config.go
  cmd/endpoint-ellipses.go
  cmd/endpoint.go
  cmd/endpoint_test.go
  cmd/format-fs.go
  cmd/fs-v1.go
  cmd/gateway-main.go
  cmd/globals.go
  cmd/logger/logger.go
  cmd/logger/utils.go
  cmd/net.go
  cmd/server-main.go
  cmd/storage-class.go
  cmd/storage-class_test.go
  cmd/typed-errors.go
  cmd/ui-errors-utils.go
  cmd/ui-errors.go
Labels: priority: high

#5912 fix: Avoid more crashes due to concurrent map usage
  cmd/bucket-handlers.go
  cmd/bucket-notification-handlers.go
  cmd/bucket-policy-handlers.go
  cmd/notification.go
  cmd/peer-rpc.go
  cmd/web-handlers.go
  pkg/event/targetlist.go
  pkg/event/targetlist_test.go
Labels: priority: high

#5920 fix: introduce isLeafDir in healing to fix the crash
  cmd/tree-walk.go
  cmd/xl-sets.go
  cmd/xl-v1-healing.go
Labels: priority: severe

#5941 fix: export policy.Resource for remote RPC policy updates
  pkg/policy/resource.go
Labels: priority: high, regression

#5969 Implement support for calculating disk usage per tenant
  browser/app/js/browser/StorageInfo.js
  browser/app/js/browser/__tests__/StorageInfo.test.js
  browser/app/js/browser/__tests__/actions.test.js
  browser/app/js/browser/actions.js
  browser/app/less/inc/header.less
  browser/ui-assets.go
  cmd/disk-cache.go
  cmd/disk-usage.go
  cmd/fs-v1-multipart_test.go
  cmd/fs-v1.go
  cmd/naughty-disk_test.go
  cmd/object-api-datatypes.go
  cmd/posix.go
  cmd/storage-interface.go
  cmd/storage-rpc-client.go
  cmd/storage-rpc-server.go
  cmd/storage-rpc-server_test.go
  cmd/xl-sets.go
  cmd/xl-v1.go
  cmd/xl-v1_test.go
  pkg/disk/disk.go
  pkg/madmin/examples/server-info.go
  pkg/madmin/info-commands.go
Labels: priority: high

#5976 Deprecate showing drive capacity and total free
  browser/app/js/browser/StorageInfo.js
  browser/app/js/browser/__tests__/StorageInfo.test.js
  browser/app/js/browser/__tests__/actions.test.js
  browser/ui-assets.go
  cmd/admin-handlers_test.go
  cmd/fs-v1.go
  cmd/posix.go
  cmd/server-startup-msg.go
  cmd/server-startup-msg_test.go
  cmd/web-handlers_test.go
  cmd/xl-sets.go
  cmd/xl-sets_test.go
  cmd/xl-v1.go
  cmd/xl-v1_test.go
  pkg/madmin/info-commands.go
Labels: priority: high
