Repository minio/minio, pull requests merged in 2019-06, with the labels that each got.

#7742 Ignore srvRecords from domain level entries
  pkg/dns/etcd_dns.go
Labels: priority: high

#7763 Fix OPA result response handling
  docs/sts/docker-compose.yml
  docs/sts/opa.md
  docs/sts/putobject.rego
  pkg/iam/policy/opa.go
Labels: regression fixed

#7770 Fix user IAM policy regression, reload policy appropriately
  cmd/iam.go
  go.mod
  go.sum
Labels: regression fixed

#7791 [sec] Match ${aws:username} exactly instead of prefix match
  go.mod
  go.sum
  pkg/iam/policy/resource.go
  pkg/iam/policy/resource_test.go
  pkg/iam/policy/resourceset_test.go
Labels: priority: high

#7799 [notify] Make sure to return when quorum is missing
  cmd/notification.go
Labels: priority: high, regression fixed

#7804 Add DeleteUser() to generate events in etcd
  cmd/admin-handlers.go
Labels: priority: high, regression fixed

#7839 Handle HEAD/GET requests for virtual DNS requests
  cmd/generic-handlers.go
  cmd/utils.go
Labels: priority: high

#7838 Check bucket & prefix after obj's for new bucket are fetched
  browser/app/js/objects/actions.js
  browser/ui-assets.go
Labels: priority: high
