Repository minio/minio, pull requests merged in 2019-07, with the labels that each got.

#7845 Ensure that we use constants everywhere
  cmd/admin-handlers.go
  cmd/api-datatypes.go
  cmd/api-headers.go
  cmd/api-response.go
  cmd/api-router.go
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/gateway-common.go
  cmd/generic-handlers.go
  cmd/handler-utils.go
  cmd/http/headers.go
  cmd/logger/message/audit/entry.go
  cmd/logger/target/http/http.go
  cmd/object-api-utils.go
  cmd/object-handlers-common.go
  cmd/object-handlers.go
  cmd/peer-rest-server.go
  cmd/server_test.go
  cmd/signature-v2.go
  cmd/signature-v4-utils.go
  cmd/signature-v4.go
  cmd/storage-rest-server.go
  cmd/streaming-signature-v4.go
  cmd/sts-errors.go
  cmd/sts-handlers.go
  cmd/utils.go
  cmd/web-handlers.go
Labels: priority: high

#7874 Avoid chown instead fallback to rootpath for user perms
  dockerscripts/check-user.go
Labels: priority: high

#7882 Support any string as delimiter for listing
  cmd/bucket-handlers-listobjects.go
  cmd/object-api-common.go
  cmd/object-api-listobjects_test.go
  cmd/xl-sets.go
  go.mod
  go.sum
Labels: priority: high

#7908 Fix mint hub.docker.com builds
  Dockerfile.mint
  mint/postinstall.sh
  mint/preinstall.sh
  mint/release.sh
Labels: priority: high

#7925 Fix dynamic help vars for sub-commands
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/s3/gateway-s3.go
  go.mod
  go.sum
Labels: regression fixed

#7914 Redirect to browser only if browser is enabled
  cmd/api-response.go
Labels: priority: high, regression fixed

#7930 Deprecate auto detection of container user
  .gitignore
  Dockerfile
  Dockerfile.dev
  Dockerfile.release
  Makefile
  dockerscripts/check-user.go
  dockerscripts/docker-entrypoint.sh
  docs/docker/README.md
Labels: priority: high

#7957 Fix to only add SRV records that match the key exactly.
  pkg/dns/etcd_dns.go
Labels: priority: severe

#7983 Do not assume all HTTP errors as Network errors
  cmd/object-api-common.go
  cmd/storage-rest-client.go
  cmd/utils.go
Labels: regression fixed
