Repository minio/minio, pull requests merged in 2019-09, with the labels that each got.

#8209 Enhancements to daily-sweeper routine to reduce CPU load
  cmd/daily-lifecycle-ops.go
  cmd/daily-sweeper.go
  cmd/xl-sets.go
Labels: priority: high

#8224 Fix etcd watch regression in IAM subsystem
  cmd/iam-etcd-store.go
Labels: regression fixed

#8232 Allow caching only in gateway mode.
  cmd/disk-cache-backend.go
  cmd/disk-cache.go
  cmd/server-main.go
  docs/disk-caching/DESIGN.md
  docs/disk-caching/README.md
Labels: priority: high

#8241 return error during part listing when no quorum
  cmd/xl-v1-multipart.go
Labels: priority: high, regression fixed

#8240 posix/readDir should populate name for DT_UKNOWN
  cmd/posix-list-dir_unix.go
Labels: priority: high, regression fixed

#8250 Wait clearing the close channel
  pkg/s3select/csv/reader.go
Labels: priority: high, regression fixed

#8239 Avoid recursion and use a simple loop to merge entries
  cmd/xl-sets.go
Labels: priority: high

#8258 Remove size query parameter from PerfInfo handler
  cmd/admin-router.go
  cmd/admin-server-info.go
Labels: regression fixed

#8261 S3 Select: Parsing tweaks
  pkg/s3select/select.go
  pkg/s3select/sql/statement.go
  pkg/s3select/sql/value.go
  pkg/s3select/sql/value_test.go
Labels: priority: high, regression fixed

#8269 Remove setting net.Conn Deadlines as its not needed anymore
  cmd/http/accountingconn.go
  cmd/http/deadlineconn.go
  cmd/http/deadlineconn_test.go
  cmd/http/listener.go
  cmd/http/listener_test.go
  cmd/http/server.go
  cmd/http/server_test.go
Labels: regression fixed

#8328 Update klauspost/reedsolomon dependency to 1.9.3
  go.mod
  go.sum
Labels: priority: high

#8304 Provide more context to error messages in STS
  cmd/sts-errors.go
  cmd/sts-handlers.go
Labels: priority: high
