Repository minio/minio, pull requests merged in 2019-05, with the labels that each got.

#7625 Fix: Handle regression caused by gorilla mux v1.7.0
  cmd/api-router.go
Labels: priority: high

#7609 Turn off md5sum optionally if content-md5 is not set
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/common-main.go
  cmd/config-common.go
  cmd/disk-cache-fs.go
  cmd/disk-cache.go
  cmd/disk-cache_test.go
  cmd/fs-v1-multipart.go
  cmd/gateway-common.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/gateway/s3/gateway-s3-metadata.go
  cmd/globals.go
  cmd/main.go
  cmd/object-api-multipart_test.go
  cmd/object-api-utils.go
  cmd/object-api-utils_test.go
  cmd/object-handlers.go
  cmd/object-handlers_test.go
  cmd/server_test.go
  cmd/test-utils_test.go
  cmd/web-handlers.go
  cmd/xl-v1-multipart.go
  cmd/xl-v1-object.go
  pkg/hash/reader.go
  pkg/hash/reader_test.go
Labels: priority: high

#7638 Sync before Close() to avoid random I/O
  cmd/posix.go
Labels: priority: high

#7396 Remove duplicate `checkPutObjectArgs` in PutObject
  cmd/fs-v1.go
  cmd/xl-v1-object.go
Labels: priority: high

#7607 Implement bulk delete
  cmd/bucket-handlers.go
  cmd/bucket-handlers_test.go
  cmd/disk-cache.go
  cmd/fs-v1.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/b2/gateway-b2.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/gateway/oss/gateway-oss.go
  cmd/gateway/s3/gateway-s3.go
  cmd/naughty-disk_test.go
  cmd/object-api-common.go
  cmd/object-api-interface.go
  cmd/posix.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/test-utils_test.go
  cmd/utils.go
  cmd/xl-sets.go
  cmd/xl-v1-object.go
  cmd/xl-v1-object_test.go
Labels: priority: high

#7199 Simplify putObject by not breaking the stream into parts
  cmd/xl-v1-healing-common_test.go
  cmd/xl-v1-object.go
Labels: priority: high

#7656 Remove an empty entry being added into XML marshal
  cmd/xl-sets.go
Labels: priority: high

#7657 File must be sync'd before closing
  cmd/posix.go
Labels: priority: high

#7654 Remove "Connection" close instead reduce MaxConns per host
  cmd/rest/client.go
  cmd/storage-rest-server.go
Labels: priority: high

#7669 Fix object share link expiry always being 7 days
  browser/app/js/objects/actions.js
  browser/ui-assets.go
Labels: regression fixed

#7663 Remove stale entry removal spurious logging
  cmd/lock-rest-server-common.go
  cmd/lock-rest-server.go
Labels: priority: high

#7676 Avoid using io.ReadFull() for WriteAll and CreateFile
  cmd/naughty-disk_test.go
  cmd/posix.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/xl-v1-metadata.go
  go.mod
  go.sum
  pkg/ioutil/ioutil.go
Labels: priority: high

#7684 Revert "cache only on GET operations"
  cmd/bucket-handlers-listobjects.go
  cmd/bucket-handlers.go
  cmd/disk-cache-backend.go
  cmd/disk-cache-fs.go
  cmd/disk-cache-utils.go
  cmd/disk-cache.go
  cmd/disk-cache_test.go
  cmd/object-handlers.go
  cmd/web-handlers.go
  docs/disk-caching/DESIGN.md
Labels: priority: severe

#7701 Properly watch for users, policies, temp users
  cmd/config-common.go
  cmd/iam.go
Labels: priority: high

#7699 Skip non-bucket DNS entry
  pkg/dns/etcd_dns.go
Labels: priority: high

#7683 allow users to change password through browser
  browser/app/js/browser/ChangePasswordModal.js
  browser/app/js/browser/__tests__/ChangePasswordModal.test.js
  browser/app/js/browser/actions.js
  browser/app/js/utils.js
  browser/app/js/web.js
  browser/app/less/inc/modal.less
  browser/package.json
  browser/ui-assets.go
  browser/yarn.lock
  cmd/iam.go
  cmd/jwt.go
  cmd/web-handlers.go
  cmd/web-handlers_test.go
Labels: priority: high
