Repository minio/minio, pull requests merged in 2020-08, with the labels that each got.

#10186 fix: quorum calculation mistake with reduced parity
  cmd/erasure-metadata.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-object_test.go
Labels: priority: high

#10185 fix: allow FS mode situations when conflicting files exist
  cmd/bucket-metadata.go
  cmd/config-common.go
  cmd/fs-v1-helpers.go
Labels: priority: high

#10175 allow server to start even with corrupted/faulty disks
  cmd/config/errors.go
  cmd/erasure-healing.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/format-erasure.go
  cmd/format-erasure_test.go
  cmd/prepare-storage.go
  cmd/storage-errors.go
  cmd/xl-storage.go
Labels: priority: high

#10208 fix: make sure to use uniform drive count calculation
  cmd/admin-handlers-config-kv.go
  cmd/config-current.go
  cmd/endpoint-ellipses.go
  cmd/endpoint-ellipses_test.go
  cmd/erasure-sets.go
  cmd/erasure-zones.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/gateway-main.go
  cmd/gateway-unsupported.go
  cmd/globals.go
  cmd/lock-rest-server.go
  cmd/object-api-interface.go
  cmd/server-main.go
  cmd/storage-rest_test.go
  cmd/xl-storage.go
Labels: priority: high

#10217 fix: Change ListBucketTargets to ListRemoteTargets
  cmd/admin-bucket-handlers.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/bucket-replication.go
  cmd/bucket-targets.go
  cmd/object-api-errors.go
  cmd/peer-rest-server.go
  docs/bucket/replication/README.md
  pkg/bucket/replication/replication.go
  pkg/madmin/remote-target-commands.go
Labels: priority: high

#10215 Support looking up environment remotely
  cmd/config/constants.go
  cmd/gateway-main.go
  cmd/server-main.go
  pkg/env/env.go
  pkg/env/web_env.go
Labels: priority: high

#10223 Fix typo in parsing non remote env variables
  pkg/env/web_env.go
Labels: priority: high

#10261 decrypt ETags in parallel around 500 at a time
  cmd/bucket-listobjects-handlers.go
  cmd/crypto/header.go
  cmd/crypto/kes.go
  cmd/encryption-v1.go
  cmd/object-api-utils.go
Labels: priority: high

#10271 fix: storageClass shouldn't set the value upon failure
  cmd/config/storageclass/storage-class.go
Labels: priority: high

#10286 fix: commonPrefixes behavior in ListObjectVersions
  cmd/object-api-listobjects_test.go
  cmd/xl-storage.go
Labels: priority: high

#10341 fix: KES http2.0 communication support
  cmd/crypto/kes.go
Labels: priority: high, regression fixed

#10346 fix: bring back delayed leaf detection in listing
  cmd/api-response.go
  cmd/erasure-sets.go
  cmd/fs-v1.go
  cmd/gateway-common.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/object-api-common.go
  cmd/os-readdir_unix.go
  cmd/tree-walk.go
  cmd/tree-walk_test.go
  cmd/xl-storage.go
Labels: priority: high

#10348 lifecycle: Accept document without expiration configuration
  pkg/bucket/lifecycle/expiration.go
  pkg/bucket/lifecycle/expiration_test.go
  pkg/bucket/lifecycle/lifecycle.go
  pkg/bucket/lifecycle/rule_test.go
Labels: priority: high

#10368 fix: refresh JWKS public keys upon failure
  .github/workflows/go.yml
  cmd/config/identity/openid/jwt.go
  cmd/config/identity/openid/jwt_test.go
Labels: regression fixed
