Repository minio/minio, pull requests merged in 2020-12, with the labels that each got.

#11005 fix: allow admins to create users
  cmd/admin-handlers-users.go
Labels: regression fixed

#10876 crawler: Missing folder heal check per set
  cmd/data-crawler.go
  cmd/data-usage-cache.go
  cmd/data-usage-cache_gen.go
  cmd/erasure-server-sets.go
  cmd/erasure.go
  cmd/metacache-entries.go
  cmd/metacache-set.go
  cmd/metacache-walk.go
Labels: priority: high

#11020 fix: etcd import paths again depend on v3.4.14 release
  cmd/config-encrypted.go
  cmd/config/dns/etcd_dns.go
  cmd/config/etcd/etcd.go
  cmd/etcd.go
  cmd/globals.go
  cmd/iam-etcd-store.go
  go.mod
  go.sum
  pkg/quick/encoding.go
  pkg/quick/quick.go
Labels: priority: high

#11019 use argon2 with sync.Pool for better memory management
  .golangci.yml
  cmd/data-crawler.go
  cmd/handler-api.go
  cmd/iam-object-store.go
  go.mod
  go.sum
  mint/run/core/aws-sdk-go/go.sum
  pkg/argon2/argon2.go
  pkg/argon2/argon2_test.go
  pkg/argon2/blake2b.go
  pkg/argon2/blamka_amd64.go
  pkg/argon2/blamka_amd64.s
  pkg/argon2/blamka_generic.go
  pkg/argon2/blamka_ref.go
  pkg/madmin/encrypt.go
  pkg/madmin/encrypt_test.go
Labels: priority: high

#11039 fix: allow sub-admin to modify password for other users
  cmd/admin-handlers-users.go
Labels: regression fixed

#11070 fix: grafana double counting for bucket usage, histrogram and objects
  docs/metrics/prometheus/grafana/minio-overview.json
Labels: priority: high

#11052 fix: refactor locks to apply them uniquely per node
  Makefile
  buildscripts/verify-build.sh
  cmd/admin-handlers.go
  cmd/endpoint.go
  cmd/erasure-multipart.go
  cmd/erasure-sets.go
  cmd/local-locker.go
  cmd/lock-rest-client.go
  cmd/lock-rest-server.go
  cmd/namespace-lock.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
  cmd/routers.go
  pkg/argon2/argon2.go
  pkg/dsync/drwmutex.go
  pkg/madmin/encrypt.go
Labels: priority: high

#11068 crawler: Stream bucket usage cache data
  cmd/data-usage-cache.go
  cmd/data-usage_test.go
  cmd/metacache-set.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
Labels: priority: high

#11097 fix: heal bucket metadata right before healing bucket
  cmd/admin-heal-ops.go
  cmd/background-heal-ops.go
  cmd/background-newdisks-heal-ops.go
  cmd/bucket-metadata-sys.go
  cmd/common-main.go
  cmd/erasure-bucket.go
  cmd/erasure-healing.go
  cmd/erasure-healing_test.go
  cmd/erasure-server-sets.go
  cmd/erasure-sets.go
  cmd/fs-v1.go
  cmd/gateway-unsupported.go
  cmd/global-heal.go
  cmd/object-api-interface.go
  cmd/server-main.go
  cmd/service.go
  cmd/storage-rest-client.go
  cmd/test-utils_test.go
Labels: priority: high

#11098 fix: remove the requirement for healing buckets in ListBucketsHeal
  cmd/admin-heal-ops.go
  cmd/background-newdisks-heal-ops.go
  cmd/bucket-metadata-sys.go
  cmd/erasure-bucket.go
  cmd/erasure-server-sets.go
  cmd/erasure-sets.go
  cmd/fs-v1.go
  cmd/gateway-unsupported.go
  cmd/metacache-set.go
  cmd/object-api-interface.go
  cmd/prepare-storage.go
  cmd/server-main.go
Labels: priority: high

#11114 Ignore ObjectNotFound errors in delete api while enforcing locking
  cmd/bucket-object-lock.go
Labels: priority: high

#11115 fix: prioritized latest buckets for crawler to finish the scans faster
  cmd/admin-heal-ops.go
  cmd/background-newdisks-heal-ops.go
  cmd/erasure-server-sets.go
  cmd/erasure-sets.go
  cmd/fs-v1.go
  cmd/object-api-utils.go
Labels: priority: high

#11124 fix: timer deadlock on expired timers
  cmd/admin-heal-ops.go
  cmd/background-newdisks-heal-ops.go
  cmd/data-crawler.go
  cmd/erasure-sets.go
Labels: priority: high

#11136 fix: delimiter based listing was broken without marker
  cmd/erasure-server-sets.go
  cmd/metacache-entries.go
  cmd/object-api-listobjects_test.go
  cmd/web-handlers.go
  mint/build/minio-py/install.sh
  mint/mint.sh
Labels: priority: high

#11138 fix: allow STS creds for admin accounts to add users
  cmd/admin-handlers-users.go
Labels: priority: high

#11143 normalize users with double // in accessKeys
  cmd/admin-handlers-users.go
  cmd/web-handlers.go
Labels: priority: high

#11142 admin: ServerInfo returns info without object layer initialized
  cmd/admin-handlers.go
  cmd/admin-server-info.go
  cmd/endpoint.go
  cmd/erasure-server-sets.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/gateway-unsupported.go
  cmd/metrics.go
  cmd/object-api-datatypes.go
  cmd/object-api-interface.go
  cmd/server-startup-msg.go
  cmd/server-startup-msg_test.go
  pkg/madmin/info-commands.go
Labels: priority: high

#11034 Encrypt remote targets while saving
  cmd/admin-bucket-handlers.go
  cmd/bucket-metadata-sys.go
  cmd/bucket-metadata.go
  cmd/bucket-metadata_gen.go
  cmd/bucket-targets.go
Labels: priority: high

#11153 fix: select always online peers for remote listing
  cmd/notification.go
  cmd/peer-rest-client.go
Labels: priority: high

#11150 fix: issues with handling delete markers in metacache
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/metacache-entries.go
  cmd/metacache-server-pool.go
  cmd/metacache-set.go
  cmd/metacache-stream.go
Labels: priority: high

#11045 refactor cmd/crypto code for SSE handling and parsing
  cmd/bucket-handlers.go
  cmd/bucket-lifecycle.go
  cmd/crypto/header.go
  cmd/crypto/header_test.go
  cmd/crypto/metadata.go
  cmd/crypto/metadata_test.go
  cmd/crypto/sse-c.go
  cmd/crypto/sse-kms.go
  cmd/crypto/sse-s3.go
  cmd/crypto/sse.go
  cmd/disk-cache-backend.go
  cmd/encryption-v1.go
  cmd/encryption-v1_test.go
  cmd/generic-handlers_test.go
  cmd/http/headers.go
  cmd/object-api-utils.go
  cmd/object-api-utils_test.go
  cmd/object-handlers.go
  cmd/object-handlers_test.go
  cmd/signature-v4-utils_test.go
  cmd/web-handlers.go
Labels: priority: high

#11156 fix: re-use bytes.Buffer using sync.Pool
  cmd/metacache-bucket.go
  cmd/metacache-set.go
  cmd/metacache-stream.go
Labels: priority: high

#11163 fix: discarding results do not attempt in-memory metacache writer
  cmd/data-crawler.go
  cmd/erasure-object.go
  cmd/global-heal.go
  cmd/metacache-set.go
  cmd/object-api-interface.go
Labels: priority: high

#11181 Fix small typo
  docs/bucket/retention/README.md
Labels: documentation
