Repository minio/minio, pull requests merged in 2020-04, with the labels that each got.

#9249 fix: use specified authToken for audit/logger HTTP targets
  cmd/config-current.go
  cmd/logger/target/http/http.go
Labels: priority: high

#9235 Do not exit on boot Verify() failure to allow rolling upgrades
  cmd/server-main.go
Labels: priority: high

#9253 fix: allow listBuckets with listBuckets permission
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/test-utils_test.go
Labels: priority: high

#9263 fix: possible connection leaks in sets init, heal
  cmd/prepare-storage.go
  cmd/xl-sets.go
Labels: priority: high

#9264 fix: Quit when the context is canceled in madmin
  pkg/madmin/api.go
  pkg/madmin/retry.go
Labels: priority: high

#9181 fix: change policies API to return and take struct
  cmd/admin-handlers-config-kv.go
  cmd/admin-handlers-users.go
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/iam.go
  pkg/madmin/README.md
  pkg/madmin/config-commands.go
  pkg/madmin/config-help-commands.go
  pkg/madmin/config-history-commands.go
  pkg/madmin/config-kv-commands.go
  pkg/madmin/group-commands.go
  pkg/madmin/kms-commands.go
  pkg/madmin/policy-commands.go
  pkg/madmin/top-commands.go
  pkg/madmin/user-commands.go
  pkg/madmin/utils.go
Labels: priority: high

#9258 increase drive OBD block size
  pkg/disk/obd.go
  pkg/madmin/obd.go
Labels: priority: high

#9297 delete: Use physical Dir() for proper prefix cleanup in Windows
  cmd/posix.go
Labels: priority: high

#9301 start watcher after all creds have been loaded
  buildscripts/race.sh
  cmd/iam-etcd-store.go
  cmd/iam-object-store.go
  cmd/iam.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
Labels: priority: high

#9272 lifecycle: Disallow delete when the object is locked
  cmd/daily-lifecycle-ops.go
  cmd/object-lock.go
Labels: priority: high

#9220 avoid unnecessary KMS requests during single-part PUT
  cmd/bucket-handlers.go
  cmd/encryption-v1.go
  cmd/encryption-v1_test.go
  cmd/object-api-utils.go
  cmd/object-handlers.go
  cmd/web-handlers.go
Labels: priority: medium

#9322 fix: regression in CopyObject not preserving ETag in --compat
  cmd/object-handlers.go
Labels: priority: high, regression fixed

#9321 fix: add missing copyright headers in some files
  cmd/config/notify/legacy.go
  pkg/disk/root-disk-unix.go
  pkg/disk/root-disk-windows.go
  pkg/env/env.go
  pkg/madmin/obd_freebsd.go
Labels: priority: high

#9326 enable --compat flag by default
  README.md
  cmd/common-main.go
  cmd/gateway/b2/gateway-b2.go
  cmd/main.go
  cmd/server-startup-msg.go
Labels: priority: high

#9323 Make multistage Dockerfile self-contained
  Dockerfile
Labels: priority: high

#9305 Object lock fix when default lock config is enabled
  cmd/api-errors.go
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/object-handlers.go
  cmd/web-handlers.go
  pkg/bucket/object/lock/lock.go
Labels: priority: high

#9320 fix: deprecate requirement of session token for service accounts
  cmd/admin-handlers-users.go
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/iam.go
  pkg/auth/credentials.go
  pkg/iam/policy/admin-action.go
  pkg/madmin/examples/add-service-account-and-policy.go
  pkg/madmin/examples/add-user-and-policy.go
  pkg/madmin/examples/get-service-account.go
  pkg/madmin/policy-commands.go
  pkg/madmin/user-commands.go
Labels: priority: high

#9324 implement configurable timeout for OBD tests
  cmd/admin-handlers.go
  cmd/admin-router.go
  pkg/disk/obd.go
  pkg/madmin/obd.go
Labels: priority: high

#9273 config: Add api requests max & deadline configs
  cmd/api-router.go
  cmd/config-current.go
  cmd/config/api/api.go
  cmd/config/api/help.go
  cmd/config/config.go
  cmd/globals.go
  cmd/handler-utils.go
  cmd/throttling.go
  docs/config/README.md
  docs/throttle/README.md
Labels: priority: high
