Repository minio/minio, pull requests merged in 2020-07, with the labels that each got.

#9980 fix: cors handling after gorilla mux update
  cmd/api-router.go
  cmd/generic-handlers.go
  cmd/routers.go
Labels: regression fixed

#9992 fix: threadwalk lockup under high load
  cmd/tree-walk-pool.go
  cmd/tree-walk-pool_test.go
Labels: priority: high, regression fixed

#9981 azure: Return success when deleting non-existent object
  cmd/api-datatypes.go
  cmd/bucket-handlers.go
  cmd/gateway/azure/gateway-azure.go
Labels: priority: high

#10003 cleanup STS docs
  docs/sts/README.md
  docs/sts/assume-role.md
  docs/sts/client-grants.md
  docs/sts/docker-compose.yml
  docs/sts/keycloak.md
  docs/sts/ldap.md
  docs/sts/opa.md
  docs/sts/putobject.rego
  docs/sts/web-identity.md
Labels: priority: high

#10004 support bootstrap client to use healthcheck restClient
  cmd/bootstrap-peer-server.go
  cmd/global-heal.go
  cmd/server-main.go
Labels: priority: high

#10020 fix: cors should be available on all paths
  cmd/api-router.go
Labels: priority: high

#10026 fix: make sure to use new restClient for healthcheck
  cmd/bootstrap-peer-server.go
  cmd/gateway/azure/gateway-azure.go
  cmd/lock-rest-client.go
  cmd/peer-rest-client.go
  cmd/rest/client.go
  cmd/storage-rest-client.go
  cmd/test-utils_test.go
  pkg/dsync/drwmutex.go
Labels: priority: high

#10025 fix: cors handling again for not just OPTIONS request
  cmd/api-router.go
  cmd/gateway-main.go
  cmd/server-main.go
Labels: priority: high

#10029 fix: deletes on older format properly
  cmd/xl-storage.go
Labels: priority: high

#10015 fix: admin info output and improve overall performance
  cmd/admin-handlers.go
  cmd/admin-server-info.go
  cmd/erasure-sets.go
  cmd/erasure-zones.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/metrics.go
  cmd/object-api-datatypes.go
  cmd/prepare-storage.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  pkg/madmin/heal-commands.go
  pkg/madmin/info-commands.go
Labels: priority: high

#10098 fix: fix lockup in merge-walk pool
  cmd/merge-walk-pool.go
  cmd/merge-walk-pool_test.go
  cmd/tree-walk-pool.go
Labels: priority: high, regression fixed
