Repository minio/minio, pull requests merged in 2021-01, with the labels that each got.

#11215 fix: calculate prometheus disks_offline/disks_total correctly
  cmd/admin-handlers.go
  cmd/erasure-server-sets.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/gateway/nas/gateway-nas.go
  cmd/gateway/s3/gateway-s3.go
  cmd/metrics.go
  cmd/object-api-interface.go
  cmd/server-startup-msg.go
Labels: priority: high

#11214 remove/deprecate crawler disable environment
  cmd/admin-bucket-handlers.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/bucket-handlers.go
  cmd/data-crawler.go
  cmd/data-usage.go
  cmd/metrics.go
Labels: priority: high

#11220 do not use large buffers if not necessary
  cmd/bitrot-streaming.go
  cmd/bitrot.go
  cmd/bitrot_test.go
  cmd/common-main.go
  cmd/erasure-decode_test.go
  cmd/erasure-heal_test.go
  cmd/erasure-healing-common_test.go
  cmd/erasure-healing.go
  cmd/erasure-healing_test.go
  cmd/erasure-metadata-utils.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-object_test.go
  cmd/erasure-utils.go
  cmd/metacache-set.go
  cmd/naughty-disk_test.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
Labels: priority: high

#11103 Allow Compression + encryption
  cmd/config/compress/compress.go
  cmd/encryption-v1.go
  cmd/object-api-getobject_test.go
  cmd/object-api-multipart_test.go
  cmd/object-api-putobject_test.go
  cmd/object-api-utils.go
  cmd/object-api-utils_test.go
  cmd/object-handlers.go
  cmd/object-handlers_test.go
  cmd/object_api_suite_test.go
  cmd/test-utils_test.go
  docs/bucket/versioning/DESIGN.md
  docs/bucket/versioning/xl-meta.go
  docs/compression/README.md
Labels: priority: high

#11229 fix: use buffers only when necessary for io.Copy()
  buildscripts/race.sh
  cmd/fs-v1-helpers.go
  cmd/fs-v1-helpers_test.go
  cmd/fs-v1-multipart.go
  cmd/fs-v1.go
  cmd/handler-api.go
  cmd/object-api-common.go
  cmd/storage-rest-server.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
  docs/shared-backend/DESIGN.md
  docs/zh_CN/shared-backend/DESIGN.md
  pkg/ioutil/append-file_nix.go
  pkg/ioutil/append-file_windows.go
  pkg/ioutil/ioutil.go
Labels: priority: high

#11236 initialize IAM store before Init() to avoid any crash
  cmd/iam.go
  cmd/server-main.go
Labels: priority: high

#11237 fix: getObject fd leaks in transition and replication code
  cmd/bucket-lifecycle.go
  cmd/bucket-replication.go
  cmd/bucket-targets.go
Labels: priority: high

#11247 expire stale locks when owner is down
  cmd/admin-server-info.go
  cmd/globals.go
  cmd/local-locker.go
  cmd/prepare-storage.go
  cmd/server-main.go
Labels: priority: high

#11257 fix: regression in adding new replication targets
  cmd/bucket-targets.go
Labels: priority: high

#11266 LDAP doc fix: remove repeated paragraph and add emphasis
  docs/sts/ldap.md
Labels: documentation

#11280 fix: make sure parentDirIsObject is used at set level
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-sets.go
  cmd/metacache-set.go
  cmd/object-api-interface.go
Labels: do not close

#10794 crypto: Escape JSON text
  cmd/crypto/json.go
  cmd/crypto/kms.go
  cmd/crypto/kms_test.go
Labels: priority: high

#11334 avoid double CORS headers in federation
  cmd/common-main.go
  cmd/generic-handlers.go
Labels: priority: high

#11338 honor maxWait heal config when maxIO hits
  cmd/admin-heal-ops.go
  cmd/background-heal-ops.go
Labels: priority: high

#11335 fix: expire locks only on participating lockers
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/admin-server-info.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/local-locker.go
  cmd/lock-rest-client.go
  cmd/lock-rest-server-common.go
  cmd/lock-rest-server.go
  cmd/prepare-storage.go
  cmd/server-main.go
  pkg/dsync/rpc-client-impl_test.go
  pkg/dsync/rpc-client-interface.go
  pkg/iam/policy/admin-action.go
  pkg/madmin/top-commands.go
Labels: priority: high

#11337 fix: LoginSTS should be an inline implementation
  cmd/api-errors.go
  cmd/web-handlers.go
Labels: priority: high

#11356 Fix replication regression
  cmd/admin-bucket-handlers.go
  cmd/bucket-replication.go
  cmd/bucket-targets.go
  cmd/http/headers.go
  cmd/object-api-interface.go
  cmd/object-api-options.go
  go.mod
  go.sum
Labels: priority: high

#11357 Bind to lookup user after user auth to lookup ldap groups
  cmd/config/identity/ldap/config.go
Labels: priority: high
