Repository minio/minio, pull requests merged in 2021-09, with the labels that each got.

#13125 fix: invalid quorum calculation in TransitionObject
  cmd/erasure-object.go
Labels: priority: severe

#13138 fix: make sure to delete dangling objects during heal
  cmd/erasure-healing_test.go
  cmd/erasure-server-pool.go
  cmd/metacache-entries.go
  internal/config/api/api.go
Labels: priority: high

#12748 sts: add support for certificate-based authentication
  cmd/admin-handlers-config-kv.go
  cmd/config-current.go
  cmd/globals.go
  cmd/sts-datatypes.go
  cmd/sts-errors.go
  cmd/sts-handlers.go
  cmd/stserrorcode_string.go
  docs/sts/tls.md
  internal/config/config.go
  internal/config/identity/tls/config.go
  internal/http/server.go
Labels: priority: high

#13171 fix: multipart replication and encrypted etag for sse-s3
  cmd/bucket-replication.go
  cmd/encryption-v1.go
  cmd/erasure-metadata.go
  cmd/erasure-multipart.go
  cmd/fs-v1-metadata.go
  cmd/fs-v1-multipart.go
  cmd/object-api-datatypes.go
  cmd/object-api-options.go
  cmd/object-api-utils.go
  cmd/object-handlers.go
Labels: priority: high

#12469 add userinfo support for OpenID
  cmd/sts-handlers.go
  docs/sts/web-identity.md
  internal/config/identity/openid/help.go
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/jwt_test.go
  internal/config/identity/openid/validators.go
  internal/config/identity/openid/validators_test.go
Labels: next-release

#13231 de-couple walkMu and walkReadMu for some granularity
  cmd/metacache-walk.go
  cmd/xl-storage.go
Labels: priority: high

#13242 fix: deleting objects was not working after upgrades
  cmd/config-common.go
  cmd/config.go
  cmd/erasure-sets.go
  cmd/xl-storage.go
Labels: priority: high
