Repository minio/minio, pull requests merged in 2021-02, with the labels that each got.

#11402 Reverting TOC due to gluegun incompatibility.
  README.md
Labels: documentation

#11465 fix: deletion of delete marker regression
  cmd/xl-storage-format-v2.go
Labels: regression fixed

#11310 read-health check endpoint returns success if cluster can serve read
  cmd/erasure-server-pool.go
  cmd/fs-v1.go
  cmd/gateway-unsupported.go
  cmd/generic-handlers.go
  cmd/healthcheck-handler.go
  cmd/healthcheck-router.go
  cmd/object-api-interface.go
  docs/metrics/healthcheck/README.md
Labels: priority: high

#11523 turn off http2 for TLS setups for now
  cmd/http/server.go
  cmd/utils.go
  go.mod
  go.sum
Labels: priority: high

#11546 default to common conditions if conditions not present
  pkg/iam/policy/action.go
  pkg/iam/policy/statement.go
Labels: priority: high

#11383 fix: Bring support for symlink on regular files on NAS
  cmd/os-readdir_other.go
  cmd/os-readdir_test.go
  cmd/os-readdir_unix.go
  cmd/os-readdir_windows.go
  docs/gateway/nas.md
Labels: do not close
