Repository minio/minio, pull requests merged in 2021-11, with the labels that each got.

#13544 remove double reads delete versions
  cmd/erasure-object.go
  cmd/naughty-disk_test.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  go.mod
  go.sum
Labels: priority: high

#13553 re-use io.Copy buffers with 32k pools
  cmd/erasure-utils.go
  cmd/fs-v1-helpers.go
  cmd/object-api-interface.go
  cmd/object-handlers.go
  cmd/s3-zip-handlers.go
  cmd/storage-rest-server.go
  cmd/warm-backend-gcs.go
  internal/ioutil/ioutil.go
Labels: priority: high

#13565 remove unnecessary RPMs to reduce security reports
  Dockerfile.release
  Dockerfile.release.fips
Labels: priority: high

#13564 Fix race in TestComputeActions test
  internal/bucket/lifecycle/lifecycle_test.go
Labels: priority: high

#13551 cache: fix commit value lookup in config
  internal/config/cache/config.go
  internal/config/cache/lookup.go
Labels: priority: high

#13582 claim exp should be integer
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/jwt_test.go
Labels: priority: high, regression fixed

#13694 allow in-memory persistence for gateway
  cmd/iam-dummy-store.go
  cmd/iam.go
Labels: regression fixed

#13682 simplify the reader for speedtest
  cmd/peer-rest-server.go
  go.mod
  go.sum
Labels: do not close

#13580 Add MaxNoncurrentVersions to NoncurrentExpiration action
  cmd/api-errors.go
  cmd/apierrorcode_string.go
  cmd/bucket-lifecycle-handlers.go
  cmd/bucket-lifecycle.go
  cmd/data-scanner.go
  cmd/object-handlers-common.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-rest-common.go
  cmd/xl-storage-format-utils.go
  cmd/xl-storage-format-utils_test.go
  cmd/xl-storage.go
  docs/bucket/lifecycle/README.md
  internal/bucket/lifecycle/lifecycle.go
  internal/bucket/lifecycle/lifecycle_test.go
  internal/bucket/lifecycle/noncurrentversion.go
Labels: do not close

#13705 Fix entries not cleared on resolve
  cmd/metacache-entries.go
Labels: priority: high

#13715 dataDir needs maxima calculation to be correct
  cmd/erasure-healing-common.go
  cmd/erasure-healing-common_test.go
Labels: priority: high

#13717 fix: obtaining a valid FileInfo in getLatestFileInfo
  buildscripts/minio-upgrade.sh
  cmd/erasure-healing-common.go
  cmd/erasure-healing-common_test.go
  cmd/erasure-healing.go
  cmd/erasure-healing_test.go
  cmd/erasure-metadata.go
Labels: priority: high
