Repository minio/minio, pull requests merged in 2021-04, with the labels that each got.

#11939 avoid network read errors crashing CreateFile call
  cmd/storage-rest-client.go
Labels: priority: high

#11942 do not use dataDir to reference inline data use versionID
  cmd/erasure-metadata.go
  cmd/erasure-object.go
  cmd/xl-storage-format-utils.go
  cmd/xl-storage-format-v2.go
  cmd/xl-storage-format-v2_test.go
  cmd/xl-storage.go
Labels: priority: high

#11962 api: Introduce metadata update APIs to update only metadata
  cmd/bucket-replication.go
  cmd/config-current.go
  cmd/config/storageclass/storage-class.go
  cmd/erasure-object.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/gateway-unsupported.go
  cmd/metacache-set.go
  cmd/naughty-disk_test.go
  cmd/object-api-interface.go
  cmd/object-handlers.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/storagemetric_string.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage-format-v2.go
  cmd/xl-storage.go
  pkg/lsync/lrwmutex.go
Labels: priority: high

#11963 add cluster support for real-time bucket stats
  cmd/bucket-handlers.go
  cmd/bucket-replication-stats.go
  cmd/bucket-replication.go
  cmd/bucket-stats.go
  cmd/bucket-stats_gen.go
  cmd/bucket-stats_gen_test.go
  cmd/metrics.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
Labels: priority: high

#11967 fix: properly close leaking bandwidth monitor channel
  cmd/admin-handlers.go
  cmd/bucket-replication.go
  cmd/data-usage-cache.go
  pkg/bucket/bandwidth/reader.go
Labels: priority: high

#12009 fix: remove auto-close in GetObjectReader
  cmd/bucket-lifecycle.go
  cmd/object-api-utils.go
  pkg/s3select/select.go
Labels: priority: high

#12020 fix: allow S3 gateway passthrough for SSE-S3 header
  cmd/api-errors.go
  cmd/object-handlers.go
  docs/gateway/s3.md
  pkg/net/url.go
Labels: priority: high

#12023 remove null version dataDir upon overwrites
  cmd/xl-storage.go
Labels: priority: high

#12032 change updateVersion to only update keys, no deletes
  cmd/bucket-lifecycle.go
  cmd/erasure-metadata.go
  cmd/xl-storage-format-v2.go
Labels: priority: high

#12051 add new pkg/fips for FIPS 140-2
  cmd/bucket-metadata.go
  cmd/crypto/key.go
  cmd/crypto/sse.go
  cmd/disk-cache-backend.go
  cmd/encryption-v1.go
  cmd/http/server.go
  cmd/object-handlers.go
  cmd/server-main.go
  pkg/fips/api.go
  pkg/fips/fips.go
  pkg/fips/no_fips.go
Labels: priority: high

#11808 ldap: Create services accounts for LDAP and STS temp accounts
  cmd/admin-handlers-users.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/apierrorcode_string.go
  cmd/auth-handler.go
  cmd/config/identity/ldap/config.go
  cmd/iam.go
  cmd/typed-errors.go
  pkg/auth/credentials.go
  pkg/iam/policy/admin-action.go
  pkg/madmin/examples/service-accounts.go
  pkg/madmin/user-commands.go
Labels: do not close, priority: high

#12058 fix: preserve shared dataDir during suspend overwrites
  cmd/xl-storage-format-v2.go
  cmd/xl-storage.go
Labels: priority: high

#12019 introduce new package pkg/kms
  cmd/admin-handlers.go
  cmd/bucket-metadata.go
  cmd/config/crypto.go
  cmd/config/crypto_test.go
  cmd/crypto/kes.go
  cmd/crypto/key.go
  cmd/crypto/key_test.go
  cmd/crypto/kms.go
  cmd/crypto/kms_test.go
  cmd/crypto/parse_test.go
  cmd/crypto/sse-c.go
  cmd/crypto/sse-kms.go
  cmd/crypto/sse-s3.go
  cmd/crypto/sse.go
  cmd/crypto/vault.go
  cmd/disk-cache-backend.go
  cmd/disk-cache-utils.go
  cmd/encryption-v1.go
  cmd/globals.go
  pkg/kms/context.go
  pkg/kms/dek_test.go
  pkg/kms/kms.go
  pkg/kms/single-key.go
  pkg/kms/single-key_test.go
Labels: priority: high

#12057 fix: do not return an error on expired credentials
  cmd/iam.go
Labels: priority: high

#12067 remove possible double locks in bandwidth monitor
  cmd/api-errors.go
  cmd/api-errors_test.go
  cmd/bucket-targets.go
  cmd/object-api-errors.go
  pkg/bucket/bandwidth/monitor.go
  pkg/bucket/bandwidth/reader.go
Labels: priority: high

#12068 fix: add helper for expected path.Clean behavior
  cmd/admin-bucket-handlers.go
  cmd/admin-handlers-users.go
  cmd/bucket-handlers.go
  cmd/data-scanner.go
  cmd/data-update-tracker.go
  cmd/iam-etcd-store.go
  cmd/utils.go
  pkg/iam/policy/resource.go
Labels: priority: high

#12069 Update Replication README to point at new docs
  docs/bucket/replication/README.md
Labels: documentation

#12116 fix: pick valid FileInfo additionally based on dataDir
  cmd/erasure-healing-common.go
  cmd/erasure-healing-common_test.go
  cmd/erasure-healing.go
  cmd/erasure-metadata-utils.go
  cmd/erasure-metadata.go
  cmd/erasure-metadata_test.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
Labels: priority: high

#12121 feat: allow prometheus for only authorized users
  cmd/metrics.go
  pkg/iam/policy/admin-action.go
  pkg/iam/policy/constants.go
Labels: priority: high

#12137 fix: reload LDAP users properly with latest mapping
  cmd/iam.go
Labels: priority: high

#12125 add support for configurable replication MRF workers
  cmd/bucket-replication-stats.go
  cmd/bucket-replication.go
  cmd/config/api/api.go
  cmd/config/api/help.go
  cmd/handler-api.go
Labels: priority: high

#12144 fix: allow parsing keys in both new and old format
  cmd/common-main.go
  docs/kms/IAM.md
  pkg/kms/single-key.go
Labels: priority: high

#12139 preserve metadata multipart restore
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/object-api-interface.go
Labels: priority: high

#12166 service accounts should use LDAP user DN to assign credentials
  cmd/admin-handlers-users.go
Labels: priority: high

#12186 fix: do not heal when disks are down
  cmd/erasure-object.go
  cmd/storage-rest-client.go
Labels: priority: high

#12184 fix: return quorum error upon decode failures
  cmd/erasure-decode.go
Labels: priority: high
