Repository minio/minio, pull requests merged in 2021-03, with the labels that each got.

#11680 fix: enforce deny if present for implicit permissions
  browser/app/js/browser/__tests__/ChangePasswordModal.test.js
  cmd/admin-handlers-users.go
  cmd/logger/logger.go
  cmd/web-handlers.go
  cmd/web-handlers_test.go
  pkg/iam/policy/policy.go
Labels: priority: high

#11682 fix: missing user policy enforcement in PostPolicyHandler
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/signature-v2.go
  cmd/signature-v2_test.go
  cmd/signature-v4.go
  cmd/signature-v4_test.go
Labels: priority: high

#11683 Avoid notification event for replicas
  cmd/bucket-replication.go
  cmd/handler-utils.go
  cmd/http/headers.go
  cmd/notification.go
  go.mod
  go.sum
Labels: priority: high

#11689 fix: prometheus metrics disks_online count when disks are down
  cmd/metrics-v2.go
  docs/metrics/prometheus/list.md
Labels: priority: high

#11800 Fix `STANDARD` defaults, point to new docs site.
  docs/erasure/storage-class/README.md
Labels: documentation

#11801 s3v4: read and verify S3 signature v4 chunks separately
  cmd/streaming-signature-v4.go
Labels: priority: high

#11805 storage write call path optimizations
  Makefile
  buildscripts/verify-build.sh
  buildscripts/verify-healing.sh
  cmd/xl-storage.go
  pkg/ioutil/ioutil.go
Labels: priority: high

#11822 [feat] Add configurable deadline for writers
  cmd/bitrot-streaming.go
  cmd/bitrot.go
  cmd/bitrot_test.go
  cmd/erasure-decode_test.go
  cmd/erasure-encode_test.go
  cmd/erasure-heal_test.go
  cmd/erasure-healing.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/iam.go
  cmd/server-main.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
  pkg/ioutil/ioutil.go
  pkg/ioutil/ioutil_test.go
Labels: priority: high

#11832 fix: handle weird drives sporadic read O_DIRECT behavior
  cmd/erasure-metadata-utils.go
  cmd/xl-storage.go
  pkg/ioutil/ioutil_test.go
Labels: priority: high

#11854 xl: CreateFile shouldn't prematurely timeout
  cmd/data-scanner.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
Labels: priority: high

#11856 avoid healObjects recursively healing at empty path
  cmd/erasure-server-pool.go
Labels: priority: high

#11855 fix: LDAP groups handling and group mapping
  cmd/admin-handlers-users.go
  cmd/auth-handler.go
  cmd/bucket-handlers.go
  cmd/iam.go
  cmd/sts-handlers.go
  pkg/bucket/policy/policy.go
  pkg/iam/policy/policy.go
Labels: priority: high

#11878 xl: CreateFile shouldn't prematurely timeout
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
Labels: priority: high

#11880 xl: remove cleanupDir instead use Delete()
  cmd/erasure-bucket.go
  cmd/erasure-object.go
  cmd/object-api-common.go
  cmd/xl-storage.go
Labels: priority: high

#11881 metrics: Add canceled requests
  cmd/admin-handlers.go
  cmd/http-stats.go
  cmd/logger/audit.go
  cmd/metrics-v2.go
  cmd/metrics.go
Labels: priority: high

#11901 highwayhash: update to latest version containing an arm64 fix
  go.mod
  go.sum
Labels: priority: high

#11902 fix: reject duplicate keys in PostPolicyJSON document
  cmd/bucket-handlers.go
  cmd/erasure-sets.go
  cmd/postpolicyform.go
  cmd/postpolicyform_test.go
Labels: priority: high

#11903 do not call LocalStorageInfo on gateways
  cmd/admin-server-info.go
Labels: regression fixed

#11910 fix: service accounts policy enforcement regression
  cmd/iam.go
Labels: regression fixed

#11923 disksWithAllParts should use parts if present
  cmd/erasure-healing-common.go
Labels: regression fixed
