Repository minio/minio, pull requests merged in 2021-07, with the labels that each got.

#12470 Add a 'free' version to track deletion of tiered object content
  cmd/bucket-lifecycle.go
  cmd/data-scanner.go
  cmd/erasure-metadata.go
  cmd/erasure-object.go
  cmd/object-api-datatypes.go
  cmd/tier-journal.go
  cmd/tier-mem-journal.go
  cmd/xl-storage-format-utils.go
  cmd/xl-storage-format-v2.go
  cmd/xl-storage-free-version.go
  cmd/xl-storage-free-version_test.go
  cmd/xl-storage.go
  go.mod
  go.sum
Labels: next-release

#12629 fix: handle redirects for specific resources
  cmd/common-main.go
  cmd/generic-handlers.go
  cmd/globals.go
  internal/config/constants.go
Labels: priority: high

#12592 feat: Add support to poll users on external SSO
  cmd/iam-etcd-store.go
  cmd/iam-object-store.go
  cmd/iam.go
  cmd/peer-rest-server.go
  cmd/sts-handlers.go
  docs/sts/keycloak.md
  internal/config/identity/openid/help.go
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/provider/keycloak.go
  internal/config/identity/openid/provider/provider.go
Labels: priority: high

#12704 feat: increase allowed maximum STS expiration timeout to 365 days
  docs/sts/assume-role.md
  docs/sts/client-grants.md
  docs/sts/ldap.md
  docs/sts/web-identity.md
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/jwt_test.go
Labels: priority: high

#12725 DOCS: Remove http links in favor of HTTPS
  docs/select/README.md
  docs/tls/README.md
Labels: documentation

#12398 heal: Add MRF metrics to background heal API response
  cmd/background-newdisks-heal-ops.go
  cmd/background-newdisks-heal-ops_gen.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/global-heal.go
  cmd/globals.go
  cmd/mrf.go
  cmd/server-main.go
  go.mod
  go.sum
Labels: do not close

#12256 Nice to have more http headers
  cmd/generic-handlers.go
Labels: do not close, external

#12788 add healing fixes for delete-marker
  cmd/erasure-healing.go
  cmd/erasure-object.go
  cmd/metacache-set.go
Labels: priority: high

#12794 improve delete-marker healing
  cmd/erasure-healing-common.go
  cmd/erasure-healing.go
Labels: priority: high

#12795 fix: avoid removing healed parts on dstDataPath
  cmd/xl-storage.go
Labels: priority: high, regression fixed

#12796 remove short circuited healing optimization
  cmd/erasure-healing-common.go
  cmd/erasure-healing.go
Labels: priority: high
