Repository minio/minio, pull requests merged in 2021-05, with the labels that each got.

#12210 feat: allow root credentials to generate STS, service accounts
  cmd/admin-handlers-users.go
  cmd/iam.go
  cmd/sts-handlers.go
Labels: priority: high

#12259 add root_disk threshold detection
  .github/workflows/go.yml
  .github/workflows/root.cert
  .github/workflows/root.key
  cmd/config/constants.go
  cmd/xl-storage.go
Labels: priority: high

#12213 lock: Timeout Unlock RPC call
  cmd/local-locker.go
  cmd/lock-rest-client.go
  cmd/lock-rest-client_test.go
  cmd/lock-rest-server.go
  pkg/dsync/drwmutex.go
  pkg/dsync/drwmutex_test.go
  pkg/dsync/dsync-server_test.go
  pkg/dsync/dsync_test.go
  pkg/dsync/rpc-client-impl_test.go
  pkg/dsync/rpc-client-interface.go
Labels: priority: high

#12275 fix: if targetUser empty use parentUser for serviceAccounts
  cmd/admin-handlers-users.go
Labels: priority: high

#12229 Dynamic usage cache
  cmd/data-scanner.go
  cmd/data-update-tracker.go
  cmd/data-usage-cache.go
  cmd/data-usage-cache_gen.go
  cmd/data-usage-cache_gen_test.go
  cmd/data-usage_test.go
  cmd/fs-v1.go
  cmd/metacache-set.go
  cmd/xl-storage.go
Labels: next-release

#12290 kms: KES client should return non-nil error when GenerateKey fails
  pkg/kms/kes.go
Labels: priority: high

#11104 Add support for syncing replica modifications
  cmd/bucket-replication.go
  cmd/object-handlers.go
  docs/bucket/replication/README.md
  pkg/bucket/replication/replication.go
  pkg/bucket/replication/replication_test.go
  pkg/bucket/replication/rule.go
  pkg/bucket/replication/rule_test.go
  pkg/bucket/replication/sourceselectioncriteria.go
Labels: next-release

#12300 fix: ensure proper usage of DataDir
  cmd/api-errors.go
  cmd/bitrot-streaming.go
  cmd/erasure-decode.go
  cmd/erasure-healing-common.go
  cmd/erasure-healing.go
  cmd/erasure-object.go
  cmd/erasure-object_test.go
Labels: priority: high

#12309 add io.ErrUnexpectedEOF for config retriable errors
  cmd/server-main.go
Labels: priority: high

#12312 fix: de-couple IAM migration and loading context from lock context
  cmd/iam.go
Labels: priority: high, regression fixed

#12311 reduce allocations on multi-disk clusters
  cmd/bitrot.go
  cmd/erasure-healing-common.go
  cmd/xl-storage.go
Labels: priority: high

#12313 fix: use key.Ciphertext for DecryptKey in KeyStatus
  cmd/admin-handlers.go
  pkg/kms/kes.go
Labels: next-release, priority: high, regression fixed

#12314 use direntPool, direntNamePool for reusable buffers
  cmd/os-readdir_unix.go
Labels: next-release, priority: high

#12321 fix: muxing order for rejected APIs
  cmd/api-router.go
Labels: regression fixed

#12334 reduce memory usage in metacache reader
  cmd/erasure-utils.go
  cmd/metacache-set.go
  cmd/metacache-stream.go
  cmd/metacache-stream_test.go
  cmd/object-api-errors.go
  go.mod
  go.sum
  pkg/ioutil/read_file.go
  pkg/ioutil/wait_pipe.go
Labels: priority: high

#12369 fix: inline data upon overwrites should be readable
  cmd/erasure-healing.go
  cmd/erasure-object.go
  cmd/erasure-object_test.go
  cmd/storage-rest-common.go
  cmd/xl-storage.go
Labels: priority: high

#12386 fix: always prefer DataBlocks present in FileInfo
  cmd/erasure-healing.go
  cmd/erasure-metadata.go
Labels: priority: high
