Repository minio/minio, pull requests merged in 2021-08, with the labels that each got.

#12851 fix: remove parentIsObject() check
  cmd/admin-handlers_test.go
  cmd/api-errors.go
  cmd/apierrorcode_string.go
  cmd/erasure-common.go
  cmd/erasure-common_test.go
  cmd/erasure-healing.go
  cmd/erasure-healing_test.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-sets.go
  cmd/fs-v1-multipart.go
  cmd/fs-v1.go
  cmd/fs-v1_test.go
  cmd/metacache-set.go
  cmd/naughty-disk_test.go
  cmd/object-api-errors.go
  cmd/object-api-interface.go
  cmd/storage-errors.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/storagemetric_string.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
  cmd/xl-storage_unix_test.go
  docs/minio-limits.md
Labels: priority: medium

#12984 always set the filter to skip navigating
  cmd/metacache-server-pool.go
  cmd/metacache-walk.go
Labels: priority: high

#12933 Add prometheus metrics for pending transition tasks
  cmd/bucket-lifecycle.go
  cmd/metrics-v2.go
Labels: do not close

#12509 Add MinIO server helm chart
  helm-reindex.sh
  helm-releases/minio-1.0.0.tgz
  helm/minio/.helmignore
  helm/minio/Chart.yaml
  helm/minio/README.md
  helm/minio/templates/NOTES.txt
  helm/minio/templates/_helper_create_bucket.txt
  helm/minio/templates/_helper_create_user.txt
  helm/minio/templates/_helpers.tpl
  helm/minio/templates/configmap.yaml
  helm/minio/templates/console-ingress.yaml
  helm/minio/templates/console-service.yaml
  helm/minio/templates/deployment.yaml
  helm/minio/templates/ingress.yaml
  helm/minio/templates/networkpolicy.yaml
  helm/minio/templates/poddisruptionbudget.yaml
  helm/minio/templates/post-install-create-bucket-job.yaml
  helm/minio/templates/post-install-create-user-job.yaml
  helm/minio/templates/pvc.yaml
  helm/minio/templates/secrets.yaml
  helm/minio/templates/securitycontextconstraints.yaml
  helm/minio/templates/service.yaml
  helm/minio/templates/statefulset.yaml
  helm/minio/values.yaml
Labels: next-release
