Repository minio/minio, pull requests merged in 2021-06, with the labels that each got.

#11914 Refactor health data structure
  cmd/admin-handlers.go
  cmd/healthinfo.go
  cmd/healthinfo_linux.go
  cmd/healthinfo_nonlinux.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
  go.mod
  go.sum
Labels: next-release

#12109 Add support for existing object replication.
  cmd/api-errors.go
  cmd/api-router.go
  cmd/apierrorcode_string.go
  cmd/bucket-handlers.go
  cmd/bucket-replication.go
  cmd/bucket-replication_test.go
  cmd/data-scanner.go
  cmd/data-usage-cache.go
  cmd/object-api-datatypes.go
  cmd/object-handlers.go
  cmd/web-handlers.go
  cmd/xl-storage.go
  docs/bucket/replication/DESIGN.md
  docs/bucket/replication/README.md
  go.mod
  go.sum
  internal/bucket/replication/replication.go
  internal/bucket/replication/rule.go
  internal/http/headers.go
Labels: next-release

#12432 fix: close the channel appropriately for dataUsageEntry
  cmd/fs-v1.go
  cmd/server-main.go
Labels: priority: high, regression fixed

#12431 fix: etcd IAM encryption fails due to incorrect kms.Context
  cmd/config-encrypted.go
  cmd/gateway-main.go
  cmd/globals.go
  cmd/iam-etcd-store.go
  cmd/iam.go
  cmd/server-main.go
Labels: priority: high, regression fixed

#12459 fix: legacy objects with 10MiB blockSize should use right buffers
  cmd/erasure-healing.go
  cmd/erasure-sets.go
  cmd/erasure.go
Labels: priority: high

#12267 Support of ZIP list/get/head as S3 extension feature
  cmd/bucket-listobjects-handlers.go
  cmd/object-handlers.go
  cmd/s3-zip-handlers.go
  docs/extensions/s3zip/README.md
  docs/extensions/s3zip/examples/aws-js/main.js
  docs/extensions/s3zip/examples/aws-js/package.json
  docs/extensions/s3zip/examples/boto3/main.py
  docs/extensions/s3zip/examples/minio-go/main.go
  go.mod
  go.sum
Labels: next-release

#12499 fix: force-delete should just rename to .trash
  cmd/xl-storage.go
Labels: next-release

#12493 fix: use madmin.Credentials for gateway interface
  cmd/gateway-interface.go
  cmd/gateway-main.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/gateway/nas/gateway-nas.go
  cmd/gateway/s3/gateway-s3.go
Labels: next-release

#12491 fix: remove unnecessary limit for queueStore
  internal/config/config.go
  internal/config/notify/help.go
  internal/config/notify/parse.go
  internal/event/target/amqp.go
  internal/event/target/queuestore.go
Labels: next-release

#12505 move internal/net to pkg/net package
  cmd/admin-handlers.go
  cmd/config-migrate.go
  cmd/consolelogger.go
  cmd/endpoint.go
  cmd/gateway-common.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/net.go
  cmd/notification.go
  cmd/object-handlers.go
  cmd/peer-rest-client.go
  cmd/s3-zip-handlers.go
  cmd/server-startup-msg.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/update.go
  go.mod
  go.sum
  internal/config/etcd/etcd.go
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/jwt_test.go
  internal/config/identity/openid/validators_test.go
  internal/config/notify/parse.go
  internal/config/policy/opa/config.go
  internal/event/target/amqp.go
  internal/event/target/elasticsearch.go
  internal/event/target/kafka.go
  internal/event/target/mqtt.go
  internal/event/target/mysql.go
  internal/event/target/nats.go
  internal/event/target/nats_contrib_test.go
  internal/event/target/nats_tls_contrib_test.go
  internal/event/target/nsq.go
  internal/event/target/nsq_test.go
  internal/event/target/postgresql.go
  internal/event/target/redis.go
  internal/event/target/webhook.go
  internal/net/health.go
  internal/net/host.go
  internal/net/host_test.go
  internal/net/port.go
  internal/net/port_test.go
  internal/net/url.go
  internal/net/url_test.go
  internal/rest/client.go
Labels: next-release

#12504 s3: Force a prefix removal using a special header
  cmd/erasure-object.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/object-api-interface.go
  cmd/object-api-options.go
  cmd/object-handlers.go
  internal/http/headers.go
Labels: next-release

#12564 docs: add limits for bucket and object name length
  docs/minio-limits.md
Labels: documentation

#12565 Clean up targets properly on bucket deletion
  cmd/bucket-targets.go
  cmd/notification.go
  cmd/peer-rest-server.go
Labels: next-release

#12544 [deps]: update jwt-go dependency
  cmd/jwt.go
  cmd/jwt_test.go
  cmd/storage-rest-server.go
  go.mod
  go.sum
  internal/auth/credentials.go
  internal/config/dns/operator_dns.go
  internal/config/identity/openid/ecdsa-sha3_contrib.go
  internal/config/identity/openid/jwt.go
  internal/config/identity/openid/rsa-sha3_contrib.go
  internal/jwt/parser.go
  internal/jwt/parser_test.go
Labels: next-release

#12545 fix: apply pre-conditions first on object metadata
  cmd/bucket-lifecycle.go
  cmd/bucket-replication.go
  cmd/disk-cache-backend.go
  cmd/erasure-object.go
  cmd/erasure-server-pool.go
  cmd/fs-v1.go
  cmd/gateway/s3/gateway-s3-sse.go
  cmd/gateway/s3/gateway-s3.go
  cmd/object-api-utils.go
Labels: next-release

#12568 allow OPA fallback for STS requests
  cmd/iam.go
  cmd/sts-handlers.go
Labels: next-release

#12554 allow resetting and reapply config on broken clusters
  cmd/admin-handlers-config-kv.go
  cmd/common-main.go
  cmd/config-current.go
  cmd/config-encrypted.go
  cmd/config.go
  cmd/object-handlers.go
  internal/config/config.go
Labels: next-release
