Repository minio/minio, pull requests merged in 2022-07, with the labels that each got.

#15220 decom IAM, Bucket metadata properly
  .github/workflows/replication.yaml
  Makefile
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-decom_gen.go
  docs/distributed/decom.sh
  docs/distributed/rw.json
Labels: priority: high

#15225 fix: decommission delete markers for non-current objects
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool.go
  docs/distributed/decom.sh
Labels: priority: high

#15161 Add detailed scanner metrics
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/background-heal-ops.go
  cmd/bucket-stats.go
  cmd/consolelogger.go
  cmd/data-scanner-metric.go
  cmd/data-scanner.go
  cmd/data-update-tracker_test.go
  cmd/data-usage-cache.go
  cmd/data-usage-cache_gen.go
  cmd/data-usage-cache_gen_test.go
  cmd/erasure-sets.go
  cmd/erasure-single-drive.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/globals.go
  cmd/http-tracer.go
  cmd/last-minute.go
  cmd/last-minute_gen.go
  cmd/last-minute_gen_test.go
  cmd/listen-notification-handlers.go
  cmd/metrics-realtime.go
  cmd/metrics-v2.go
  cmd/notification.go
  cmd/os-instrumented.go
  cmd/os-readdir_other.go
  cmd/os-readdir_unix.go
  cmd/os-readdir_windows.go
  cmd/osmetric_string.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/scannermetric_string.go
  cmd/server-startup-msg.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/update.go
  cmd/utils.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  go.mod
  go.sum
  internal/config/heal/heal.go
  internal/event/event.go
  internal/event/name.go
  internal/ioutil/read_file.go
  internal/logger/audit.go
  internal/logger/logger.go
  internal/logger/message/log/entry.go
  internal/logger/target/http/http.go
  internal/logger/target/kafka/kafka.go
  internal/logger/targets.go
  internal/pubsub/mask.go
  internal/pubsub/pubsub.go
  internal/pubsub/pubsub_test.go
Labels: priority: medium, next-release

#15152 Add external IDP management Admin API for OpenID
  cmd/admin-handlers-idp-config.go
  cmd/admin-router.go
  cmd/api-errors.go
  cmd/apierrorcode_string.go
  internal/config/config.go
  internal/config/identity/openid/help.go
  internal/config/identity/openid/openid.go
Labels: priority: medium, next-release

#15232 fix: calculate scanner metric paths for single drive
  cmd/data-scanner-metric.go
Labels: next-release

#15231 fix: allow certain mutations on objects during decommissioning
  cmd/erasure-server-pool.go
Labels: next-release

#15250 fix: do not pass around sync.Map
  cmd/erasure-sets.go
  internal/logger/target/console/console.go
Labels: priority: high

#15297 Updating minio-go
  go.mod
  go.sum
Labels: fixed

#14684 Allow topologySpreadConstraints configuration
  helm/minio/templates/statefulset.yaml
  helm/minio/values.yaml
Labels: priority: low, community, do-not-close

#15020 add annotations to ServiceMonitor
  helm/minio/templates/servicemonitor.yaml
  helm/minio/values.yaml
Labels: priority: low, community, do-not-close

#15091 replication: Add API to return unreplicated objects
  cmd/admin-bucket-handlers.go
  cmd/admin-router.go
  cmd/bucket-replication-utils.go
  cmd/bucket-replication.go
  cmd/object-api-datatypes.go
  cmd/xl-storage-format-v2.go
  go.sum
Labels: priority: medium

#15017 Optionally run a command when completing jobs
  helm/minio/templates/post-install-create-bucket-job.yaml
  helm/minio/templates/post-install-create-policy-job.yaml
  helm/minio/templates/post-install-create-user-job.yaml
  helm/minio/templates/post-install-custom-command.yaml
  helm/minio/values.yaml
Labels: priority: low, community, do-not-close

#14958 chore(deps): Included dependency review
  .github/workflows/depsreview.yaml
Labels: priority: low, community, do-not-close

#15429 do not allow filesystem fallback in server download
  cmd/update.go
Labels: priority: high

#15430 fix: regression in resolving the right versions
  buildscripts/resolve-right-versions.sh
  cmd/erasure-object.go
Labels: regression fixed
