Repository minio/minio, pull requests merged in 2022-01, with the labels that each got.

#14009 fix: initialize new drwMutex for each attempt in 'for {' loop.
  cmd/data-scanner.go
  cmd/iam.go
  cmd/server-main.go
Labels: priority: high

#14017 fix: audit log to support object names in multipleObjectNames() handler
  Makefile
  cmd/api-datatypes.go
  cmd/bucket-handlers.go
  cmd/bucket-handlers_test.go
  cmd/bucket-quota.go
  cmd/bucket-replication-utils.go
  cmd/data-scanner.go
  cmd/erasure-object_test.go
  cmd/object-handlers.go
  cmd/server_test.go
  cmd/utils.go
  docs/debugging/xl-meta/main.go
  internal/logger/audit.go
  internal/logger/logger.go
  internal/logger/message/audit/entry.go
  internal/logger/message/log/entry.go
  internal/logger/reqinfo.go
  internal/logger/target/console/console.go
Labels: priority: high

#14012 feat: decommission feature for pools
  cmd/admin-handlers-pools.go
  cmd/admin-router.go
  cmd/endpoint-ellipses.go
  cmd/endpoint.go
  cmd/erasure-common.go
  cmd/erasure-object.go
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-decom_gen.go
  cmd/erasure-server-pool-decom_gen_test.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/erasure-sets_test.go
  cmd/notification.go
  cmd/object-api-datatypes.go
  cmd/object-api-interface.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-datatypes_gen_test.go
  docs/distributed/DECOMMISSION.md
  internal/bucket/lifecycle/lifecycle.go
  internal/bucket/lifecycle/transition.go
Labels: do not close, priority: high

#14096 fix: use renameAll instead of deleteObject() for purging temporary files
  cmd/erasure-healing.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/xl-storage.go
Labels: priority: high

#14093 Ignore version not found in deleteVersions
  cmd/xl-storage.go
  cmd/xl-storage_test.go
Labels: priority: high

#14102 reject changing pools when there are pending decommissions in-progress
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-decom_test.go
  cmd/test-utils_test.go
Labels: priority: high

#14095 lock: Fix decision when a lock needs to be removed
  internal/dsync/drwmutex.go
  internal/dsync/dsync_test.go
Labels: priority: high

#14128 support site replication to replicate IAM users,groups
  cmd/admin-bucket-handlers.go
  cmd/admin-handlers-site-replication.go
  cmd/admin-handlers-users.go
  cmd/erasure.go
  cmd/iam-store.go
  cmd/site-replication.go
  docs/site-replication/run-multi-site-minio-idp.sh
  go.mod
  go.sum
Labels: priority: high

#14135 use dnscache resolver for resolving command line endpoints
  cmd/bootstrap-peer-server.go
  cmd/common-main.go
  cmd/endpoint.go
  cmd/net.go
  cmd/prepare-storage.go
  cmd/server-main.go
  go.mod
  go.sum
Labels: priority: high

#14154 fix: correct parentUser lookup for OIDC auto expiration
  cmd/iam-store.go
  cmd/iam.go
  cmd/sts-handlers.go
Labels: priority: high

#14159 docs: add decommission docs about pool removal
  docs/distributed/DECOMMISSION.md
Labels: priority: high

#14148 speed up startup sequence for all operations
  cmd/background-newdisks-heal-ops.go
  cmd/config.go
  cmd/data-update-tracker.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/format-erasure.go
  cmd/format-erasure_test.go
  cmd/globals.go
  cmd/prepare-storage.go
  cmd/tree-walk_test.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
  internal/ioutil/ioutil.go
  internal/ioutil/read_file.go
Labels: priority: high

#14168 ignore remote disks with diskID empty as offline
  cmd/erasure-sets.go
Labels: priority: high

#14117 prometheus: Publish XL storage API latency
  cmd/bucket-stats.go
  cmd/last-minute.go
  cmd/last-minute_gen.go
  cmd/last-minute_gen_test.go
  cmd/metrics-v2.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/xl-storage-disk-id-check.go
Labels: priority: high

#14170 cached diskIDs are not needed for scanner healing
  cmd/data-scanner.go
  cmd/data-usage-cache.go
  cmd/data-usage-cache_gen.go
  cmd/data-usage_test.go
  cmd/erasure.go
  cmd/fs-v1.go
  cmd/utils.go
  cmd/xl-storage.go
Labels: priority: high

#14208 fix: possible crash if private.key is empty
  internal/config/certs.go
  internal/config/certs_test.go
Labels: priority: high

#14212 ignore disk metrics for single drive mode
  cmd/metrics-v2.go
Labels: priority: high

#14206 remove FIFO bucket quota, use ILM expiration instead
  cmd/bucket-quota.go
  cmd/data-usage-cache.go
  cmd/disk-cache-utils.go
  cmd/erasure-server-pool.go
  cmd/fs-v1.go
  cmd/object-api-interface.go
  cmd/object-handlers.go
  cmd/server-main.go
  docs/bucket/quota/README.md
  go.mod
  go.sum
Labels: do-not-close
