Repository minio/minio, pull requests merged in 2022-04, with the labels that each got.

#14570 Use S3 client for uploads/downloads during perf test
  cmd/admin-handlers.go
  cmd/globals.go
  cmd/handler-api.go
  cmd/perf-tests.go
Labels: priority: high

#14719 pass the necessary query params for remote NSSCanner
  cmd/storage-rest-client.go
Labels: priority: severe

#14729 Fix service account privilege escalation
  cmd/admin-handlers-users.go
  cmd/admin-handlers-users_test.go
  cmd/sts-handlers_test.go
Labels: priority: high, regression fixed

#14753 fix: IAM reload should only list at config/iam/ precisely
  cmd/iam-object-store.go
Labels: priority: high

#14757 cancel active routine only after metadata has been saved
  cmd/erasure-server-pool-decom.go
Labels: priority: high

#14780 fix: replication deleteObject() regression and CopyObject() behavior
  cmd/erasure-object.go
  cmd/object-handlers.go
  cmd/xl-storage.go
Labels: priority: high

#14613 attempt to real resolve when there is a quorum failure on reads
  .github/workflows/go-healing.yml
  Makefile
  buildscripts/cicd-corpus/disk1/bucket/testobj/2b4f7e41-df82-4a5e-a3c1-8df87f83332f/part.1
  buildscripts/cicd-corpus/disk2/bucket/testobj/2b4f7e41-df82-4a5e-a3c1-8df87f83332f/part.1
  buildscripts/cicd-corpus/disk2/bucket/testobj/xl.meta
  buildscripts/cicd-corpus/disk3/bucket/testobj/2b4f7e41-df82-4a5e-a3c1-8df87f83332f/part.1
  buildscripts/cicd-corpus/disk3/bucket/testobj/xl.meta
  buildscripts/cicd-corpus/disk4/bucket/testobj/2b4f7e41-df82-4a5e-a3c1-8df87f83332f/part.1
  buildscripts/cicd-corpus/disk4/bucket/testobj/a599bd9e-69fe-49b7-b6bf-fe53021039d5/part.1
  buildscripts/cicd-corpus/disk4/bucket/testobj/xl.meta
  buildscripts/cicd-corpus/disk5/bucket/testobj/2b4f7e41-df82-4a5e-a3c1-8df87f83332f/part.1
  buildscripts/cicd-corpus/disk5/bucket/testobj/a599bd9e-69fe-49b7-b6bf-fe53021039d5/part.1
  buildscripts/cicd-corpus/disk5/bucket/testobj/xl.meta
  buildscripts/resolve-right-versions.sh
  cmd/erasure-healing-common.go
  cmd/erasure-healing_test.go
  cmd/erasure-object.go
  cmd/naughty-disk_test.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-datatypes_gen_test.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/storagemetric_string.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
Labels: priority: high

#14822 fix: support decommissioning directory objects
  cmd/erasure-server-pool-decom.go
Labels: priority: high

#14829 allow service accounts and temp credentials site-level healing
  cmd/iam-store.go
  cmd/iam.go
  cmd/site-replication.go
Labels: priority: high

#14842 JWKS should be parsed before usage
  go.mod
  go.sum
  internal/config/identity/openid/jwt.go
Labels: priority: high
