Repository minio/minio, pull requests merged in 2022-02, with the labels that each got.

#14221 fs: Retry listing if no marker
  cmd/fs-v1.go
Labels: priority: high

#14104 Add API for removing site(s) from site replication
  cmd/admin-handlers-site-replication.go
  cmd/admin-router.go
  cmd/site-replication.go
Labels: priority: high

#14182 add support for drive speedtest
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/speedtest.go
  cmd/utils.go
  go.mod
  go.sum
Labels: priority: high

#13413 Tier metrics prometheus
  cmd/metrics-v2.go
  docs/metrics/prometheus/list.md
Labels: do-not-close

#14227 Add ability to use custom commands
  helm/minio/templates/_helper_custom_command.txt
  helm/minio/templates/configmap.yaml
  helm/minio/templates/post-install-custom-command.yaml
  helm/minio/values.yaml
Labels: community

#14398 fix: clientId must be unique for all servers
  internal/event/target/mqtt.go
Labels: regression fixed

#14402 reject speedtest when there isn't enough disk space available
  cmd/admin-handlers.go
Labels: priority: high

#14418 Removing Azure, GCS, HDFS gateway implementations
  cmd/gateway-interface.go
  cmd/gateway/azure/gateway-azure.go
  cmd/gateway/azure/gateway-azure_test.go
  cmd/gateway/gateway.go
  cmd/gateway/gcs/gateway-gcs.go
  cmd/gateway/gcs/gateway-gcs_test.go
  cmd/gateway/hdfs/gateway-hdfs-utils.go
  cmd/gateway/hdfs/gateway-hdfs.go
  cmd/metrics.go
  docs/gateway/README.md
  docs/gateway/azure.md
  docs/gateway/gcs.md
  docs/gateway/hdfs.md
  go.mod
  go.sum
  helm/minio/templates/gateway-deployment.yaml
  helm/minio/templates/secrets.yaml
  helm/minio/values.yaml
Labels: do-not-close
