Repository minio/minio, pull requests merged in 2023-04, with the labels that each got.

#17024 fix: regression in counting total requests
  cmd/generic-handlers.go
  cmd/handler-utils.go
  cmd/http-stats.go
  cmd/http-tracer.go
  cmd/routers.go
  internal/http/request-recorder.go
  internal/http/stats/http-traffic-recorder.go
  internal/logger/audit.go
Labels: priority: high

#17025 fix: do not error out if the local bucket is missing
  cmd/peer-s3-client.go
Labels: priority: high

#17081 Add tags to auditLogLifecycle
  cmd/bucket-lifecycle.go
  cmd/data-scanner.go
  cmd/erasure-object.go
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-rebalance.go
  cmd/erasure-server-pool.go
  cmd/metacache-server-pool.go
  cmd/object-api-interface.go
  cmd/object-handlers-common.go
  cmd/object-handlers.go
Labels: do-not-close

#17089 allow root user to be disabled via config settings
  .github/workflows/root-disable.yml
  Makefile
  buildscripts/disable-root.sh
  cmd/admin-handlers-users.go
  cmd/auth-handler_test.go
  cmd/globals.go
  cmd/handler-api.go
  cmd/iam.go
  cmd/jwt.go
  cmd/jwt_test.go
  cmd/signature-v4-utils.go
  cmd/site-replication.go
  internal/config/api/api.go
  internal/config/api/help.go
Labels: needs-docs
