Repository minio/minio, pull requests merged in 2023-03, with the labels that each got.

#16803 Do not allow adding root user to IAM subsystem
  cmd/admin-handlers-users.go
  cmd/sts-handlers_test.go
Labels: priority: high

#16812 restore rotating root credentials properly
  cmd/auth-handler.go
  cmd/iam-etcd-store.go
  cmd/iam-object-store.go
Labels: regression (fixed)

#16849 fix: post policy request security bypass
  cmd/api-router.go
  cmd/auth-handler.go
Labels: priority: severe

#16852 fix: convert '\' to '/' on windows
  cmd/generic-handlers.go
Labels: priority: high

#16939 docs: Specify correct port in docker-compose README.md
  docs/orchestration/docker-compose/README.md
Labels: documentation
