Repository minio/minio, pull requests merged in 2023-08, with the labels that each got.

#17796 sts: validate if iam subsystem initialized in handlers
  cmd/sts-errors.go
  cmd/sts-handlers.go
  cmd/stserrorcode_string.go
Labels: next-release

#17791 fix: crash in globalTierJournal when TierConfig is not initialized
  cmd/globals.go
  cmd/server-main.go
  cmd/tier-journal.go
  cmd/tier-mem-journal.go
Labels: next-release

#17856 Removing deprecated var from minio helm
  helm/minio/templates/deployment.yaml
  helm/minio/templates/statefulset.yaml
Labels: community

#17864 Minor change to text under license page
  README.md
Labels: bugfix

#17944 Clarify Community Helm Chart
  helm/minio/README.md
Labels: documentation

#17955 fix: read atomic variable in clientDevNull round trip time
  cmd/admin-handlers.go
Labels: external-contribution
