Repository minio/minio, pull requests merged in 2023-11, with the labels that each got.

#18368 Fix hanging scanner saves
  cmd/data-usage-cache.go
Labels: regression (fixed)

#18393 skip speedtest bucket from site-replication
  cmd/admin-handlers.go
Labels: priority: high

#18394 replace io.Discard usage to fix some NUMA copy() latencies
  cmd/admin-handlers-site-replication.go
  cmd/admin-handlers.go
  cmd/erasure-utils.go
  cmd/peer-rest-server.go
  cmd/perf-tests.go
  cmd/storage-rest-client.go
  go.mod
  go.sum
  internal/config/lambda/target/webhook.go
  internal/event/target/elasticsearch.go
  internal/event/target/webhook.go
  internal/http/close.go
  internal/ioutil/discard.go
  internal/s3select/select.go
Labels: priority: high

#18422 Fixing a file consistency issue on SFTP upload
  cmd/sftp-server-driver.go
Labels: bugfix

#18508 snowball-repl: Add support of immediate tiering
  cmd/batch-handlers.go
  cmd/object-handlers.go
Labels: priority: high

#18542 Fixed transition rules getting overwritten while healing
  cmd/site-replication.go
  docs/bucket/replication/setup_ilm_expiry_replication.sh
Labels: priority: high

#18549 Improve env var config error reporting
  cmd/bootstrap-peer-server.go
Labels: priority: high
