Repository minio/minio, pull requests merged in 2024-01, with the labels that each got.

#18109 scanner: Allow full throttle if there is no parallel disk ops
  cmd/data-scanner.go
  cmd/data-usage_test.go
  cmd/erasure.go
  cmd/naughty-disk_test.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
Labels: priority: high, next-release

#18727 fix: an odd crash when deleting `null` DEL markers
  .github/workflows/replication.yaml
  Makefile
  cmd/xl-storage-format-v2.go
  docs/bucket/versioning/versioning-tests.sh
Labels: regression (fixed)

#18777 avoid disk monitoring leaks under various conditions
  cmd/erasure-sets.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
Labels: priority: high, next-release

#18778 fix: a typo in storeDataUsageInBackend() comment
  cmd/data-usage.go
Labels: needs-review

#18819 capture I/O in waiting and total tokens in diskMetrics
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-rest-common.go
  cmd/xl-storage-disk-id-check.go
Labels: priority: medium, next-release, needs-review

#18807 Use +Inf label additionally for Histogram metrics
  cmd/metrics-v2.go
  cmd/metrics-v2_test.go
Labels: priority: medium, next-release, needs-review

#18828 fix: remove policy mapping file when empty
  cmd/iam-store.go
Labels: priority: medium, next-release, needs-review

#18826 introduce new ServiceV2 API to handle guided restarts
  cmd/admin-handlers.go
  cmd/admin-handlers_test.go
  cmd/admin-router.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
Labels: priority: medium, new-feature, performance/optimize, next-release, needs-review

#18836 add new drive I/O waiting/tokens metric
  cmd/erasure.go
  cmd/metrics-v2.go
  docs/metrics/prometheus/list.md
  go.mod
  go.sum
Labels: needs-docs, new-feature, next-release, needs-review

#18831 improve server update behavior by re-using memory properly
  cmd/admin-handlers.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/update.go
Labels: performance/optimize, next-release, needs-review

#18837 compress binary while sending it to all the nodes
  cmd/admin-handlers.go
  cmd/notification.go
  cmd/peer-rest-server.go
  cmd/update.go
Labels: new-feature, next-release, needs-review

#18785 site replication: remove extraneous log for missing group
  cmd/site-replication.go
Labels: priority: medium, next-release, needs-review

#18846 pre-allocate memory by default
  cmd/common-main.go
  cmd/erasure-server-pool.go
  cmd/globals.go
  cmd/server-main.go
Labels: new-feature, performance/optimize, needs-review

#18650 Helm: add cilium networkpolicy
  helm/minio/README.md
  helm/minio/templates/ciliumnetworkpolicy.yaml
  helm/minio/templates/networkpolicy.yaml
  helm/minio/values.yaml
Labels: priority: low, community

#18781 feat(chart): add support to set the display name of OpenID provider
  helm/minio/templates/deployment.yaml
  helm/minio/templates/statefulset.yaml
  helm/minio/values.yaml
Labels: priority: low, community, needs-review

#18770 Helm: Add apiVersion and kind to the StatefulSets volumeClaimTemplates
  helm/minio/templates/statefulset.yaml
Labels: priority: low, community

#18611 Correct a mistake in the value.yaml of minio helm chart
  helm/minio/values.yaml
Labels: priority: low, community

#18854 add necessary protection err, fileInfo slice reads and writes
  Makefile
  buildscripts/unaligned-healing.sh
  cmd/common-main.go
  cmd/erasure-healing-common.go
  cmd/erasure-healing.go
  cmd/erasure-metadata.go
  cmd/erasure-object.go
Labels: priority: high, next-release

#18862 Add separate grid reconnection mutex
  internal/grid/connection.go
  internal/grid/grid_test.go
Labels: bugfix, needs-review

#18860 fix: Re-use TCP connections for Kafka dials
  internal/event/target/kafka.go
  internal/logger/target/kafka/kafka.go
Labels: bugfix

#18855 migrate bootstrap logic directly to websockets
  Makefile
  cmd/admin-handlers.go
  cmd/bootstrap-peer-server.go
  cmd/bootstrap-peer-server_gen.go
  cmd/bootstrap-peer-server_gen_test.go
  cmd/endpoint.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/format-erasure.go
  cmd/grid.go
  cmd/handler-api.go
  cmd/prepare-storage.go
  cmd/routers.go
  cmd/server-main.go
  cmd/storage-errors.go
  cmd/utils.go
  cmd/xl-storage.go
  internal/grid/handlers.go
  internal/grid/handlers_string.go
Labels: priority: high, next-release, needs-review

#18868 further bootstrap/startup optimization for reading 'format.json'
  cmd/erasure-common.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/format-erasure.go
  cmd/global-heal.go
  cmd/metrics-resource.go
  cmd/naughty-disk_test.go
  cmd/object-api-utils.go
  cmd/peer-rest-server.go
  cmd/prepare-storage.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-datatypes_gen_test.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  internal/grid/handlers.go
  internal/grid/handlers_string.go
Labels: priority: high, performance/optimize

#18871 Fix inspect format.json exclusion
  cmd/admin-handlers.go
Labels: bugfix

#18873 allow bucket import to be idempotent
  cmd/admin-bucket-handlers.go
Labels: priority: high, bugfix

#18859 add new update v2 that updates per node, allows idempotent behavior
  cmd/admin-handlers.go
  cmd/admin-router.go
  cmd/common-main.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/update.go
  go.mod
  go.sum
Labels: new-feature

#18880 fix: regression in internode bytes counting
  internal/grid/connection.go
  internal/grid/manager.go
  internal/grid/trace.go
Labels: priority: high, next-release, needs-review

#18882 update() stale rebalance stats() object during pool expansion
  cmd/background-newdisks-heal-ops.go
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-rebalance.go
Labels: priority: high, next-release, needs-review

#18884 add missing proper error return in WalkDir()
  cmd/metacache-walk.go
  cmd/storage-rest-client.go
Labels: priority: high, next-release, needs-review

#18889 grid: Simpler reconnect logic
  internal/grid/connection.go
  internal/grid/handlers.go
  internal/grid/muxclient.go
  internal/grid/muxserver.go
Labels: priority: high, next-release, needs-review

#18890 avoid close 'nil' panics if any
  cmd/admin-handlers.go
  cmd/admin-heal-ops.go
  cmd/batch-expire.go
  cmd/batch-handlers.go
  cmd/bucket-lifecycle.go
  cmd/bucket-replication.go
  cmd/data-scanner.go
  cmd/erasure-decode.go
  cmd/erasure-object.go
  cmd/erasure-server-pool-rebalance.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/ftp-server-driver.go
  cmd/global-heal.go
  cmd/iam-object-store.go
  cmd/iam.go
  cmd/metacache-entries.go
  cmd/metacache-server-pool.go
  cmd/metacache-set.go
  cmd/metacache-stream.go
  cmd/metacache-walk.go
  cmd/metrics-v2.go
  cmd/notification.go
  cmd/object-api-utils.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
  cmd/perf-tests.go
  cmd/server-main.go
  cmd/service.go
  cmd/sftp-server-driver.go
  cmd/speedtest.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  internal/dsync/drwmutex.go
  internal/grid/connection.go
  internal/grid/debug.go
  internal/grid/handlers.go
  internal/grid/muxclient.go
  internal/grid/muxserver.go
  internal/ioutil/ioutil.go
  internal/logger/target/http/http.go
  internal/logger/target/kafka/kafka.go
  internal/store/store.go
Labels: priority: high, next-release, needs-review

#18886 remove local disk metrics from cluster metrics
  cmd/erasure-server-pool.go
  cmd/metrics-v2.go
  docs/metrics/prometheus/alerts.md
  docs/metrics/prometheus/grafana/grafana-minio.png
  docs/metrics/prometheus/grafana/minio-dashboard.json
  docs/metrics/prometheus/list.md
Labels: priority: high, needs-docs, next-release, needs-review

#18905 Add cgroup v2 support for memory limit
  cmd/erasure-server-pool.go
  cmd/handler-api.go
  internal/bpool/bpool.go
  internal/bpool/bpool_test.go
Labels: bugfix

#18917 remove checkBucketExist check entirely to avoid fan-out calls
  cmd/bitrot-streaming.go
  cmd/bitrot.go
  cmd/bitrot_test.go
  cmd/bucket-replication.go
  cmd/erasure-decode_test.go
  cmd/erasure-encode_test.go
  cmd/erasure-heal_test.go
  cmd/erasure-healing-common_test.go
  cmd/erasure-healing.go
  cmd/erasure-healing_test.go
  cmd/erasure-metadata-utils.go
  cmd/erasure-metadata.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-object_test.go
  cmd/erasure-server-pool.go
  cmd/erasure-sets.go
  cmd/metacache-server-pool.go
  cmd/metacache-set.go
  cmd/metacache-walk.go
  cmd/naughty-disk_test.go
  cmd/object-api-input-checks.go
  cmd/object-api-listobjects_test.go
  cmd/object-api-multipart_test.go
  cmd/object-api-putobject_test.go
  cmd/object-api-utils_test.go
  cmd/peer-s3-client.go
  cmd/post-policy_test.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-interface.go
  cmd/storage-rest-client.go
  cmd/storage-rest-common.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
Labels: performance/optimize, needs-review

#18903 Improve tracing & notification scalability
  cmd/admin-handlers.go
  cmd/endpoint.go
  cmd/globals.go
  cmd/listen-notification-handlers.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
  cmd/routers.go
  internal/grid/handlers.go
  internal/grid/handlers_string.go
  internal/grid/types.go
  internal/pubsub/pubsub.go
Labels: performance/optimize

#18921 add total usable capacity, free and used to DataUsageInfo()
  cmd/admin-handlers.go
  cmd/data-usage-utils.go
Labels: next-release, needs-review

#18922 remove all the frivolous logs, that may or may not be actionable
  cmd/bitrot-streaming.go
  cmd/bitrot-whole.go
  cmd/erasure-coding.go
  cmd/erasure-decode.go
  cmd/erasure-encode.go
  cmd/erasure-metadata-utils.go
  cmd/erasure-object.go
  cmd/erasure-utils.go
  cmd/erasure.go
Labels: next-release, needs-review
