Repository minio/minio, pull requests merged in 2024-06, with the labels that each got.

#19539 Add ILM metrics in metrics-v3
  cmd/metrics-v2.go
  cmd/metrics-v3-ilm.go
  cmd/metrics-v3.go
  docs/metrics/v3.md
Labels: new-feature, needs-review

#19796 Two way streams fixes - take 2
  internal/grid/benchmark_test.go
  internal/grid/connection.go
  internal/grid/debug.go
  internal/grid/debugmsg_string.go
  internal/grid/grid_test.go
  internal/grid/muxclient.go
  internal/grid/muxserver.go
  internal/grid/stream.go
Labels: bugfix, new-feature, needs-review

#19903 turn-off unexpected debug logging in List() calls
  cmd/metacache-entries.go
Labels: priority: high

#19920 load credential for in-flights requests as singleflight
  cmd/iam-store.go
  cmd/iam.go
  go.mod
Labels: performance/optimize, needs-review

#19939 skip healing properly in the scanner when a drive is hotplugged
  cmd/background-newdisks-heal-ops.go
  cmd/data-scanner.go
  cmd/data-usage-cache.go
  cmd/data-usage-cache_gen.go
  cmd/data-usage_test.go
  cmd/erasure-healing-common_test.go
  cmd/erasure-server-pool.go
  cmd/erasure.go
  cmd/object-api-interface.go
  cmd/xl-storage.go
Labels: priority: high

#19956 Removing timeout on shutdown
  cmd/common-main.go
  cmd/globals.go
  cmd/server-main.go
  internal/http/server.go
  internal/http/server_test.go
Labels: code cleanup

#19835 Add `AccessKeysListLDAPBulk` function to allow listing accesskeys for multiple/all users in one call
  cmd/admin-handlers-idp-ldap.go
  cmd/admin-router.go
  cmd/iam-store.go
  cmd/iam.go
  go.mod
  go.sum
Labels: new-feature
