Repository minio/minio, pull requests merged in 2024-04, with the labels that each got.

#18949 Add env variable MINIO_IDENTITY_OPENID_REDIRECT_URI to statefulset
  helm/minio/templates/statefulset.yaml
Labels: community, bugfix

#19421 fix: a regression in IAM policy reload routine()
  cmd/iam-object-store.go
  cmd/iam.go
  cmd/signature-v4-utils_test.go
Labels: priority: high, regression (fixed)

#19465 handle missing LDAP normalization in SetPolicy() API
  cmd/iam.go
  cmd/sts-handlers_test.go
Labels: bugfix

#19466 avoid busy loops in bad path component
  cmd/admin-handlers.go
  cmd/generic-handlers.go
Labels: bugfix

#19460 allow protection from invalid config values
  cmd/config-current.go
  cmd/utils.go
  internal/config/browser/browser.go
  internal/config/drive/drive.go
  internal/config/heal/heal.go
  internal/config/ilm/ilm.go
  internal/config/scanner/scanner.go
Labels: bugfix

#19452 Add drive metrics in metrics-v3
  cmd/metrics-resource.go
  cmd/metrics-v3-cache.go
  cmd/metrics-v3-system-drive.go
  cmd/metrics-v3.go
  docs/metrics/v3.md
Labels: do-not-close, new-feature

#19428 fix: close sessionPolicyFile in the sts-assume-role example
  docs/sts/assume-role.go
Labels: community, bugfix, needs-review

#19621 deprecate usage of sha256-simd
  CREDITS
  docs/debugging/s3-verify/go.mod
  docs/debugging/s3-verify/go.sum
  go.mod
  go.sum
  internal/hash/sha256/sh256.go
  internal/hash/sha256/sh256_fips.go
Labels: priority: high, next-release

#19232 helm: fix port types in CiliumNetworkPolicy
  helm/minio/templates/ciliumnetworkpolicy.yaml
  helm/minio/templates/statefulset.yaml
Labels: community, bugfix

#19245 helm support loadBalancerSourceRanges and externalTrafficPolicy
  helm/minio/templates/console-service.yaml
  helm/minio/templates/service.yaml
  helm/minio/values.yaml
Labels: community, bugfix, new-feature
