Repository minio/minio, pull requests merged in 2024-08, with the labels that each got.

#20228 enhance getActualSize() to return valid values for most situations
  cmd/bucket-replication.go
  cmd/encryption-v1.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/metacache-entries.go
  cmd/object-api-options.go
  cmd/object-api-utils.go
  cmd/object-api-utils_test.go
  cmd/xl-storage-format-utils.go
  cmd/xl-storage-format-utils_test.go
  cmd/xl-storage.go
  cmd/xl-storage_test.go
Labels: regression (fixed)

#19410 heal: Persist MRF queue in the disk during shutdown
  cmd/background-newdisks-heal-ops.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-server-pool.go
  cmd/globals.go
  cmd/mrf.go
  cmd/mrf_gen.go
  cmd/mrf_gen_test.go
  cmd/peer-s3-client.go
  cmd/signals.go
Labels: priority: high, new-feature

#20278 [fix] S3Select: Add some missing input validation
  internal/s3select/csv/args.go
Labels: do-not-close

#20320 do not fallback on the drives to load groups for LDAP
  cmd/iam-store.go
Labels: priority: high
