Repository minio/minio, pull requests merged in 2024-03, with the labels that each got.

#19100 xl: Avoid called getdents for folders in listing
  cmd/is-dir-empty_linux.go
  cmd/is-dir-empty_other.go
  cmd/xl-storage.go
Labels: performance/optimize

#19025 automatically generate root credentials with KMS
  CREDITS
  cmd/admin-bucket-handlers.go
  cmd/admin-handler-utils.go
  cmd/bucket-encryption-handlers.go
  cmd/common-main.go
  cmd/config-current.go
  cmd/encryption-v1.go
  cmd/kms-handlers.go
  cmd/metrics-v2.go
  cmd/server-startup-msg.go
  go.mod
  go.sum
  internal/auth/credentials.go
  internal/auth/credentials_test.go
  internal/kms/config.go
  internal/kms/identity-manager.go
  internal/kms/kes.go
  internal/kms/key-manager.go
  internal/kms/kms.go
  internal/kms/policy-manager.go
  internal/kms/single-key.go
  internal/kms/status-manager.go
Labels: new-feature, needs-review

#18926 Improve expiration of tiered objects
  cmd/bucket-lifecycle.go
  cmd/config-current.go
  cmd/data-scanner.go
  cmd/data-scanner_test.go
  cmd/erasure-metadata.go
  cmd/erasure-metadata_test.go
  cmd/erasure-object.go
  cmd/erasure-server-pool.go
  cmd/globals.go
  cmd/handler-api.go
  cmd/metrics-v2.go
  cmd/object-api-interface.go
  cmd/server-main.go
  cmd/tier-journal.go
  cmd/tier-journal_gen.go
  cmd/tier-journal_gen_test.go
  cmd/tier-journal_test.go
  cmd/tier-mem-journal.go
  cmd/tier-sweeper.go
  cmd/xl-storage-free-version.go
  cmd/xl-storage-free-version_test.go
  cmd/xl-storage.go
  internal/config/api/api.go
  internal/config/api/help.go
  internal/config/config.go
  internal/config/errors.go
  internal/config/ilm/help.go
  internal/config/ilm/ilm.go
Labels: performance/optimize

#18768 Add clientId existing secret option
  helm/minio/templates/deployment.yaml
  helm/minio/templates/statefulset.yaml
  helm/minio/values.yaml
Labels: priority: low, community

#19171 Add common middleware to S3 API handlers
  cmd/admin-router.go
  cmd/api-router.go
  cmd/api-utils.go
  cmd/http-stats.go
  cmd/metrics-v2.go
  cmd/metrics-v2_test.go
  cmd/metrics.go
  cmd/tier.go
  docs/bucket/replication/delete-replication.sh
  docs/bucket/replication/setup_2site_existing_replication.sh
  docs/bucket/replication/setup_3site_replication.sh
  docs/bucket/replication/sio-error.sh
Labels: new-feature, needs-review

#19174 avoid too much auditing during decom/rebalance make it more robust
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-rebalance.go
  cmd/object-api-interface.go
  cmd/utils.go
  docs/debugging/pprofgoparser/main.go
  internal/logger/logger.go
  internal/logger/reqinfo.go
  internal/logger/target/http/http.go
Labels: bugfix, performance/optimize

#19068 feat: Add Metrics V3 API
  cmd/data-usage-utils.go
  cmd/generic-handlers.go
  cmd/globals.go
  cmd/http-stats.go
  cmd/metrics-resource.go
  cmd/metrics-router.go
  cmd/metrics-v2.go
  cmd/metrics-v2_gen.go
  cmd/metrics-v2_gen_test.go
  cmd/metrics-v3-api.go
  cmd/metrics-v3-cache.go
  cmd/metrics-v3-cluster-erasure-set.go
  cmd/metrics-v3-cluster-health.go
  cmd/metrics-v3-cluster-usage.go
  cmd/metrics-v3-handler.go
  cmd/metrics-v3-system-drive.go
  cmd/metrics-v3-system-network.go
  cmd/metrics-v3-types.go
  cmd/metrics-v3.go
  cmd/notification.go
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
  cmd/tier.go
  docs/metrics/v3.md
Labels: new-feature

#19235 update all dependencies
  CREDITS
  go.mod
  go.sum
Labels: bugfix, new-feature, performance/optimize, needs-review

#19265 allow dynamically changing max_object_versions per object
  cmd/handler-api.go
  cmd/xl-storage-format-v2.go
  internal/config/api/api.go
  internal/config/api/help.go
Labels: new-feature, performance/optimize, needs-review

#19262 implement a flag to specify custom crossdomain.xml
  cmd/common-main.go
  cmd/crossdomain-xml-handler.go
  cmd/globals.go
  cmd/server-main.go
Labels: new-feature, needs-review

#19287 fix: add a default requests deadline when deadline is 0
  cmd/handler-api.go
Labels: priority: high, next-release

#19289 add deprecated expiry_workers to be ignored
  internal/config/api/api.go
  internal/config/errors.go
Labels: priority: high, next-release

#19288 add additional logs for the decom during metadata save
  cmd/erasure-server-pool-decom.go
Labels: priority: high, next-release

#19285 feat: add user to NOTIFY_REDIS
  internal/config/notify/help.go
  internal/config/notify/legacy.go
  internal/config/notify/parse.go
  internal/event/target/redis.go
Labels: bugfix, new-feature, needs-review

#19275 Webhook targets refactor and bug fixes
  cmd/config-current.go
  internal/logger/target/http/http.go
  internal/logger/targets.go
  internal/store/queuestore.go
  internal/store/store.go
Labels: bugfix, new-feature

#19360 set max versions to be IntMax to avoid premature failures
  cmd/handler-api.go
  cmd/xl-storage-format-v2.go
  internal/config/api/api.go
Labels: priority: high

#19365 fix: avoid fan-out DeletePrefix calls for batch-expire and ILM
  cmd/batch-expire.go
  cmd/data-scanner.go
Labels: priority: high

#19359 expire ILM all versions verify quorum on action
  cmd/erasure-object.go
Labels: priority: high, next-release

#19361 use bigger partSize per part for tiering to MinIO
  cmd/warm-backend-minio.go
Labels: priority: high, next-release

#19358 ldap: improve normalization of DN values
  cmd/admin-handlers-idp-ldap.go
  cmd/iam.go
  cmd/sts-handlers_test.go
  go.mod
  go.sum
  internal/config/identity/ldap/ldap.go
Labels: priority: high, next-release

#19107 Enable replication of SSE-C objects
  Makefile
  cmd/bucket-handlers.go
  cmd/bucket-replication.go
  cmd/erasure-multipart.go
  cmd/erasure-object.go
  cmd/generic-handlers.go
  cmd/generic-handlers_test.go
  cmd/handler-utils.go
  cmd/object-api-options.go
  cmd/object-handlers.go
  cmd/object-multipart-handlers.go
  docs/bucket/versioning/versioning-tests.sh
  docs/site-replication/run-sse-kms-object-replication.sh
  docs/site-replication/run-ssec-object-replication-with-compression.sh
  docs/site-replication/run-ssec-object-replication.sh
  internal/bucket/replication/replication.go
  internal/bucket/replication/replication_test.go
  internal/crypto/error.go
  internal/http/headers.go
Labels: new-feature
