Repository minio/minio, pull requests merged in 2024-05, with the labels that each got.

#19640 fix: a crash in RemoveReplication target
  cmd/admin-bucket-handlers.go
  cmd/bucket-replication.go
  cmd/bucket-targets.go
  cmd/data-scanner.go
  cmd/site-replication.go
Labels: priority: high

#19672 support 'mc support perf object' with root login disabled
  cmd/admin-handlers.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/perf-tests.go
  cmd/speedtest.go
Labels: next-release

#19669 return appropriate error upon reaching maxClients()
  cmd/api-errors.go
  cmd/handler-api.go
Labels: next-release

#19368 kms: add support for MinKMS and remove some unused/broken code
  cmd/admin-bucket-handlers.go
  cmd/admin-handlers.go
  cmd/api-errors.go
  cmd/batch-rotate.go
  cmd/bucket-encryption-handlers.go
  cmd/bucket-metadata.go
  cmd/common-main.go
  cmd/config-current.go
  cmd/encryption-v1.go
  cmd/globals.go
  cmd/healthcheck-handler.go
  cmd/kms-handlers.go
  cmd/kms-router.go
  cmd/metrics-v2.go
  cmd/object_api_suite_test.go
  cmd/site-replication.go
  go.mod
  go.sum
  internal/config/crypto.go
  internal/config/crypto_test.go
  internal/crypto/sse-kms.go
  internal/crypto/sse-s3.go
  internal/kms/config.go
  internal/kms/config_test.go
  internal/kms/conn.go
  internal/kms/dek_test.go
  internal/kms/errors.go
  internal/kms/identity-manager.go
  internal/kms/kes.go
  internal/kms/key-manager.go
  internal/kms/kms.go
  internal/kms/policy-manager.go
  internal/kms/secret-key.go
  internal/kms/secret-key_test.go
  internal/kms/single-key.go
  internal/kms/status-manager.go
Labels: bugfix, new-feature

#19699 Fix incorrect merging of slash-suffixed objects
  cmd/metacache-entries.go
Labels: bugfix, needs-review

#19695 Added decom test with KES using sse-s3 and sse-kms
  Makefile
  docs/distributed/decom-encrypted-kes.sh
Labels: new-feature, needs-review

#19707 Move /system/go to /debug/go
  cmd/metrics-v3.go
  docs/metrics/v3.md
Labels: new-feature, needs-review

#19714 Add more metrics to v3/cluster/erasure-set
  cmd/metrics-v3-cluster-erasure-set.go
  cmd/metrics-v3.go
  docs/metrics/v3.md
Labels: new-feature, needs-review

#19605 Add PutObject Ring Buffer
  cmd/bitrot-streaming.go
  cmd/erasure-decode.go
  cmd/erasure-encode.go
  internal/http/transports.go
  internal/ringbuffer/LICENSE
  internal/ringbuffer/README.md
  internal/ringbuffer/ring_buffer.go
  internal/ringbuffer/ring_buffer_benchmark_test.go
  internal/ringbuffer/ring_buffer_test.go
Labels: performance/optimize, needs-review

#19733 Capture ttfb api metrics only for GetObject
  cmd/http-stats.go
Labels: new-feature, needs-review

#19688 Add sufficient deadlines and countermeasures to handle hung node scenario
  .github/workflows/go-cross.yml
  .github/workflows/go-fips.yml
  .github/workflows/go-healing.yml
  .github/workflows/go-lint.yml
  .github/workflows/go.yml
  .github/workflows/helm-lint.yml
  .github/workflows/iam-integrations.yaml
  .github/workflows/mint.yml
  .github/workflows/mint/minio-resiliency.yaml
  .github/workflows/replication.yaml
  .github/workflows/root-disable.yml
  .github/workflows/run-mint.sh
  .github/workflows/shfmt.yml
  .github/workflows/upgrade-ci-cd.yaml
  buildscripts/disable-root.sh
  cmd/admin-server-info.go
  cmd/common-main.go
  cmd/erasure-healing.go
  cmd/erasure-multipart.go
  cmd/erasure-server-pool.go
  cmd/globals.go
  cmd/grid.go
  cmd/peer-s3-client.go
  cmd/post-policy_test.go
  cmd/server-main.go
  cmd/storage-rest-server.go
  internal/config/drive/drive.go
  internal/config/drive/help.go
  internal/deadlineconn/deadlineconn.go
  internal/grid/connection.go
  internal/http/dial_linux.go
  internal/http/listener.go
  internal/ioutil/ioutil.go
  internal/ioutil/ioutil_test.go
Labels: priority: high, performance/optimize, needs-review

#19546 Add cluster and bucket replication metrics in metrics-v3
  cmd/metrics-v3-api.go
  cmd/metrics-v3-bucket-replication.go
  cmd/metrics-v3-replication.go
  cmd/metrics-v3-types.go
  cmd/metrics-v3.go
  docs/metrics/v3.md
Labels: new-feature, needs-review

#19690 Use point in time values for `gauge` metrics in graphs
  docs/metrics/prometheus/grafana/bucket/minio-bucket.json
Labels: do-not-close, bugfix

#19805 fix: authenticate LDAP via actual DN instead of normalized DN
  cmd/admin-handlers-idp-ldap.go
  cmd/admin-handlers-users.go
  cmd/ftp-server-driver.go
  cmd/iam-store.go
  cmd/iam.go
  cmd/sftp-server.go
  cmd/sts-handlers.go
  cmd/sts-handlers_test.go
  go.mod
  go.sum
  internal/config/identity/ldap/ldap.go
Labels: regression (fixed)

#19832 fix: single node multi-drive must register local drives properly
  cmd/erasure-server-pool.go
Labels: regression (fixed)
