Repository minio/minio, pull requests merged in 2024-02, with the labels that each got.

#18951 move Make,Delete,Head,Heal bucket calls to websockets
  cmd/endpoint.go
  cmd/peer-rest-server.go
  cmd/peer-s3-client.go
  cmd/peer-s3-server.go
  internal/grid/handlers.go
  internal/grid/handlers_string.go
  internal/grid/trace.go
Labels: performance/optimize

#18979 calculate correct quorum check for metadata updates on object
  cmd/erasure-object.go
Labels: priority: high, next-release, needs-review

#18974 Add missing gob register for map[string]string{}
  cmd/common-main.go
Labels: priority: high, next-release, needs-review

#18988 Add websocket TCP write timeouts
  internal/grid/connection.go
Labels: priority: high, bugfix, next-release

#18987 Fix second muxclient context leak
  internal/grid/connection.go
Labels: priority: high, bugfix, next-release

#18954 Enable expired-object-all-versions
  internal/bucket/lifecycle/expiration.go
  internal/bucket/lifecycle/expiration_test.go
Labels: priority: high, bugfix, next-release

#18999 do not block iam.store registration
  cmd/erasure-healing_test.go
  cmd/iam.go
  cmd/object-handlers_test.go
  cmd/object_api_suite_test.go
Labels: bugfix, needs-review

#19005 Add GetBucketInfo toStorageErr conversion
  cmd/peer-s3-client.go
Labels: bugfix

#19017 Fix blocked streams blocking reconnects
  internal/grid/connection.go
  internal/grid/debug.go
  internal/grid/grid_test.go
  internal/grid/muxclient.go
  internal/grid/stream.go
Labels: bugfix

#19009 optimize startup sequence performance
  cmd/bucket-metadata-sys.go
  cmd/bucket-metadata.go
  cmd/erasure-server-pool.go
  cmd/storage-rest-client.go
  internal/grid/connection.go
  internal/grid/grid.go
Labels: performance/optimize

#19018 Fix shared top locks client
  cmd/notification.go
Labels: bugfix

#19038 honor replaced disk properly by updating globalLocalDrives
  cmd/erasure-sets.go
  cmd/erasure.go
  cmd/globals.go
  cmd/metrics-v2.go
  cmd/peer-rest-server.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-rest-common.go
  docs/metrics/prometheus/list.md
Labels: bugfix

#19036 FIx unexpected behavior when creating service account
  cmd/api-errors.go
  cmd/apierrorcode_string.go
  cmd/iam.go
  internal/auth/credentials.go
Labels: bugfix

#19041 upgrade all deps
  CREDITS
  README.md
  go.mod
  go.sum
Labels: performance/optimize

#19049 Refresh tier config periodically
  cmd/tier-handlers.go
  cmd/tier.go
Labels: bugfix

#19060 log: Add logger.Event to send to console and other logger targets
  cmd/admin-heal-ops.go
  cmd/api-response.go
  cmd/background-newdisks-heal-ops.go
  cmd/erasure-server-pool-decom.go
  cmd/erasure-server-pool-rebalance.go
  cmd/ftp-server.go
  cmd/global-heal.go
  cmd/server-main.go
  cmd/xl-storage-disk-id-check.go
  internal/logger/logger.go
  internal/logger/target/console/console.go
  internal/rest/client.go
Labels: bugfix, needs-review

#19004 Convert more peer peer REST calls
  cmd/admin-handlers.go
  cmd/local-locker.go
  cmd/local-locker_gen.go
  cmd/local-locker_gen_test.go
  cmd/metacache-set.go
  cmd/metacache-set_gen.go
  cmd/metacache-set_gen_test.go
  cmd/metrics-v2.go
  cmd/metrics-v2_gen.go
  cmd/metrics-v2_gen_test.go
  cmd/peer-rest-client.go
  cmd/peer-rest-common.go
  cmd/peer-rest-server.go
  cmd/peer-s3-client.go
  cmd/storage-datatypes.go
  cmd/storage-datatypes_gen.go
  cmd/storage-datatypes_gen_test.go
  cmd/storage-rest-client.go
  cmd/storage-rest-server.go
  cmd/tier-last-day-stats.go
  cmd/tier-last-day-stats_gen.go
  cmd/tier-last-day-stats_gen_test.go
  internal/bucket/bandwidth/monitor.go
  internal/bucket/bandwidth/monitor_gen.go
  internal/bucket/bandwidth/monitor_gen_test.go
  internal/grid/handlers.go
  internal/grid/handlers_string.go
  internal/grid/manager.go
  internal/grid/types.go
Labels: priority: medium, new-feature

#18801 allow renames() for inlined writes without data-dir
  cmd/xl-storage.go
Labels: priority: medium, bugfix, needs-review

#19086 site-repl: Fix endpoint in the error with unexpected deployment-id
  cmd/site-replication.go
Labels: bugfix, needs-review

#19087 Add missing yaml syntax highlighting to docs/metrics/prometheus/README.md
  docs/metrics/prometheus/README.md
Labels: community, bugfix

#19088 use typos instead of codespell
  .codespellrc
  .github/workflows/codespell.yml
  .github/workflows/typos.yml
  .typos.toml
  cmd/admin-handlers.go
  cmd/admin-handlers_test.go
  cmd/api-errors.go
  cmd/api-response.go
  cmd/apierrorcode_string.go
  cmd/auth-handler_test.go
  cmd/bucket-handlers_test.go
  cmd/bucket-listobjects-handlers.go
  cmd/bucket-replication-stats.go
  cmd/erasure-healing-common.go
  cmd/erasure-healing_test.go
  cmd/erasure-object.go
  cmd/handler-utils_test.go
  cmd/metrics-v2.go
  cmd/object-api-errors.go
  cmd/object-api-multipart_test.go
  cmd/object-api-putobject_test.go
  cmd/object-api-utils_test.go
  cmd/object-handlers_test.go
  cmd/object_api_suite_test.go
  cmd/server_test.go
  cmd/signature-v4-parser_test.go
  cmd/sts-errors.go
  cmd/xl-storage-format_test.go
  cmd/xl-storage.go
  internal/bucket/object/lock/lock_test.go
  internal/config/config.go
  internal/config/notify/parse.go
  internal/crypto/header.go
  internal/dsync/drwmutex.go
  internal/logger/logger.go
  internal/logger/target/kafka/kafka.go
  internal/s3select/csv/reader.go
  internal/s3select/sql/jsonpath.go
Labels: bugfix, code cleanup, needs-review

#19123 fix: crash in ResourceMetrics RPC handling concurrent writers
  cmd/peer-rest-client.go
  cmd/peer-rest-server.go
Labels: priority: high

#19143 initialize the disk healer early on
  buildscripts/verify-healing.sh
  cmd/background-heal-ops.go
  cmd/background-newdisks-heal-ops.go
  cmd/bucket-lifecycle.go
  cmd/common-main.go
  cmd/data-scanner.go
  cmd/data-scanner_test.go
  cmd/erasure-server-pool.go
  cmd/global-heal.go
  cmd/globals.go
  cmd/mrf.go
  cmd/server-main.go
  cmd/service.go
  cmd/storage-rest-server.go
  cmd/xl-storage.go
Labels: bugfix

#19142 heal: Add skipped objects to the heal summary
  cmd/background-newdisks-heal-ops.go
  cmd/background-newdisks-heal-ops_gen.go
  cmd/global-heal.go
  go.mod
  go.sum
Labels: new-feature

#19137 cachevalue: simplified exported interface
  cmd/admin-handlers-users.go
  cmd/bucket-quota.go
  cmd/data-usage.go
  cmd/erasure-server-pool.go
  cmd/metrics-v2.go
  cmd/storage-rest-client.go
  cmd/xl-storage-disk-id-check.go
  cmd/xl-storage.go
  internal/cachevalue/cache.go
  internal/cachevalue/cache_test.go
Labels: new-feature

#19161 Update metrics list.md with new metrics from RELEASE.2024-01-05
  docs/metrics/prometheus/list.md
Labels: documentation
