Repository minio/minio, pull requests merged in 2024-07, with the labels that each got.

#19679 Add batch status API
  cmd/admin-router.go
  cmd/batch-expire.go
  cmd/batch-handlers.go
  cmd/batch-rotate.go
Labels: new-feature

#20056 Fix documentation for removal of delete markers ILM rule
  docs/bucket/lifecycle/README.md
Labels: documentation

#20076 Add DecodeDN and QuickNormalizeDN functions to LDAP config
  cmd/admin-handlers-idp-ldap.go
  cmd/iam-store.go
  cmd/iam.go
  go.mod
  go.sum
  internal/config/identity/ldap/ldap.go
Labels: bugfix

#20119 remove unnecessary LRU for internode auth token
  CREDITS
  cmd/common-main.go
  cmd/globals.go
  cmd/jwt.go
  cmd/jwt_test.go
  cmd/lock-rest-server-common_test.go
  cmd/object-lambda-handlers.go
  cmd/storage-rest-server.go
  cmd/storage-rest_test.go
  cmd/test-utils_test.go
  go.mod
  go.sum
  internal/grid/debug.go
  internal/grid/grid.go
  internal/grid/manager.go
  internal/grid/msg.go
  internal/rest/client.go
Labels: priority: high
