Repository minio/minio, pull requests merged in 2025-03, with the labels that each got.

#21018 Update typos config
  .typos.toml
Labels: bugfix

#21017 Update ssh and jws libs for fixed CVEs
  go.mod
  go.sum
Labels: bugfix, security

#19566 fix(templates): replace dash with underscore
  helm/minio/templates/NOTES.txt
Labels: community, bugfix, needs-review
